$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1402041961425.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e74a7a1e840a44eaabec5a02a6510cea",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"90770aef0ec0430cbeacacecaddca246",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":301},
            "size":{
              "width":530,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7abedd662d194ecd9899163cbc39fde2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":301},
                "size":{
                  "width":530,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"848b3ea6905440e2ae4ee2723cf5596e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":716,
              "y":491},
            "size":{
              "width":290,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f0012225bb4930b5dde5a35d7d9546",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":716,
                  "y":491},
                "size":{
                  "width":290,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"ab9647097e974f22a0397778a7f0e67d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":1000,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab6d5bc79064b48930dccb15b8c7bcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":1000,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"da9ab326c85b45cd91a5be270aaf1e78",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"098f6692061a4f21bb82326c9d701ce3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0a87e1103f7442edb3a851713de76ff9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"980ec942accc4c42976aaf3de115d01e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9bb71bebd799460f89341f7f13793d4e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":712,
              "y":235},
            "size":{
              "width":80,
              "height":27}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索界面 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"129cc84db06946009a57f0806a95ca9f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":235},
            "size":{
              "width":518,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"46f8dae0f8124583b388bc77089013d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":661},
            "size":{
              "width":276,
              "height":529}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06557629260643d182b293fe09c4e309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":661},
                "size":{
                  "width":276,
                  "height":529}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"4eacbbfec00848d0bb11fc0720adadd8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":752,
              "y":564},
            "size":{
              "width":95,
              "height":27}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 登陆 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"登陆.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"102a58d7dbb04034afca3aa0969bedc6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":876,
              "y":564},
            "size":{
              "width":95,
              "height":27}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索界面 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"91a60a37b1b0467a8f12d372e2a20b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":208,
              "y":637},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec57ff5282a34865b0c08a91d04a5c32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":208,
                  "y":637},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc2a08b60bb643789d6d60a83b6f363c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":214,
              "y":661},
            "size":{
              "width":494,
              "height":249}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87b6791916cc47eea5b0fdc7e3deab0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":214,
                  "y":661},
                "size":{
                  "width":494,
                  "height":249}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"2d076e7bef144ecf9c03d38681490d98",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":214,
              "y":661},
            "size":{
              "width":112,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"332d50a6ef5b47b99a99cbc33d7acde4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":214,
                  "y":661},
                "size":{
                  "width":112,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"c3859a13f95742dfa911bd286519c23e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":661},
            "size":{
              "width":112,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f31e3bcae864169a399073126101ec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":661},
                "size":{
                  "width":112,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"77bf7a9a02154eec8afc9367123aee4e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":474,
              "y":661},
            "size":{
              "width":112,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8edd20794a9b48a39f303eda2ba8c2fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":474,
                  "y":661},
                "size":{
                  "width":112,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"1c431f44ab9240b39ddee0e11ae9dd10",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":596,
              "y":661},
            "size":{
              "width":112,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db9ad850ad3249ebabe6dce8f5ef6c08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":596,
                  "y":661},
                "size":{
                  "width":112,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"93ab2e03d87648fba7de6180c542e874",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":214,
              "y":781},
            "size":{
              "width":112,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66b3b9ffe4534c64a1d9af0be0eaa2f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":214,
                  "y":781},
                "size":{
                  "width":112,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"b8f3ed36562a4c3a81efb3bd77a40655",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":781},
            "size":{
              "width":112,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53d124929b4b4333bd3e9dbfc8842c7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":781},
                "size":{
                  "width":112,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"4dbb14ce29c84168a14aa6a55b510f32",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":474,
              "y":781},
            "size":{
              "width":112,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f18535c79c9405c9ded58b39feba17e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":474,
                  "y":781},
                "size":{
                  "width":112,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"995fdea1ce68482ca27f1461e51b8a42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":596,
              "y":781},
            "size":{
              "width":112,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"070d94794fde497e8c8f1b654d3dac93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":596,
                  "y":781},
                "size":{
                  "width":112,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"afbb7fbb228a4eed95f65bf3ede43451",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":214,
              "y":940},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8224cef397614f5ab6a45bbe511399ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":214,
                  "y":940},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf05c4f7ce6d44ef9067d4743a099ee9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":214,
              "y":964},
            "size":{
              "width":494,
              "height":226}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88bf7358d2e349e5bd7bd9b96fa54500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":214,
                  "y":964},
                "size":{
                  "width":494,
                  "height":226}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"ed668f100e554afbad305b8b44c4d9cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":214,
              "y":964},
            "size":{
              "width":242,
              "height":226}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3038f9c4df44338bbb38a3bc35150e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":214,
                  "y":964},
                "size":{
                  "width":242,
                  "height":226}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u40.png"}},
{
          "id":"6de2bdde18534e50aff0244bf9b65974",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":529,
              "y":964},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1298bee229f74abcbadf8304142871f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":529,
                  "y":964},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16189265208140d08e77482d6041cd07",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":493,
              "y":1023},
            "size":{
              "width":183,
              "height":137}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"868dc0cfa23e404588362faec76b5e56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":493,
                  "y":1023},
                "size":{
                  "width":183,
                  "height":137}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d80bac0b238b4791a8948364ef2661ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":0,
              "y":1210},
            "size":{
              "width":1000,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f64f965085ed4b21ab8e9fb8a00734ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":0,
                  "y":1210},
                "size":{
                  "width":1000,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u46.png"}},
{
          "id":"08a1a5e25e1c4054aeb3af94cc39cdc0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":637},
            "size":{
              "width":178,
              "height":278}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f87e8f8bce524e6b9990247e299f4939",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":637},
                "size":{
                  "width":178,
                  "height":278}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u48.png"}},
{
          "id":"d434eb498ad7455190c9774bd1df3044",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":716,
              "y":300},
            "size":{
              "width":290,
              "height":191}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"210af42bd48e45b299f114534bdb6fd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":716,
                  "y":300},
                "size":{
                  "width":290,
                  "height":191}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u50.png"}},
{
          "id":"5ddc9beb4b8d4c0f8f7041f0bbfc153c",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":301},
            "size":{
              "width":140,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61eab2a085d143ebb73a39c80fd2be55",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":140,
                  "height":300}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c18b81ca753648e9a0c640d07acbb1a9",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"52ffaf4536474738baa10e109550dc59",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u54.png"}},
{
                  "id":"b610716b3e1643a3a216433f95d74c31",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"599f19cded7444a898f3409d239e613f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u54.png"}},
{
                  "id":"690d6071515f481d8845e75ad7efb2b4",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":210},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"021b58e646404892a00c465f53515634",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":210},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u54.png"}},
{
                  "id":"05d9954f6edb4619a113914a458a6698",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c319687549f948519cd3f21fa78138c9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u54.png"}},
{
                  "id":"50b3eb00cabf45a89518e030ea3e9db1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f08fcfca19df4e10a6e7d41b7479d9b6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":90},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u54.png"}},
{
                  "id":"1ce6f54f71554f58be44fc779339c1a8",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"01be9003e4e540ab8a8f46b2a3f197d1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":120},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u54.png"}},
{
                  "id":"64a726f55a6544289aa9da0d9863c7c9",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ca5477e777a34104b32e869bb7a0a0a5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":150},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u54.png"}},
{
                  "id":"900bf12812ab4720aaa3da379e298342",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe42a76ae03e4c5d8f4c1d285bc4bba5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":180},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u54.png"}},
{
                  "id":"a63c59b8a7f44c408b8120188239e50b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":270},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0fa1b54102e644e1a10aa978deb5c975",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":270},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u72.png"}},
{
                  "id":"9bb1478d1c504bf4ad24c5470c0860bf",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff6f2a198d6a4dd6ada526619f7e82ad",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":240},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u54.png"}}]},
{
              "id":"deda7fef11414da7baf1a6e2b98fdd94",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":0},
                "size":{
                  "width":100,
                  "height":60},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4bd629569a6c4d90ab66797d79683c7a",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eaab1cb9e9684af39cb45a77c47796b7",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"680f3d9996174cdcb5d9ad310c3b49fc",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":100,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open 搜索界面 in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"搜索界面.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/home/u76.png"}},
{
                      "id":"3edd402d879f4b73864e85c8b7693b55",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":100,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5ca0b3fbf7a04490a68210f3e8e3637e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":20},
                            "size":{
                              "width":100,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u76.png"}},
{
                      "id":"a03d616bcdfe415b9857fe837850cf63",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":100,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1ae81996e97c4641a24ec9f13b9d78f3",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":40},
                            "size":{
                              "width":100,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u80.png"}}]}],
              "parentCellId":"c18b81ca753648e9a0c640d07acbb1a9"}]},
{
          "id":"fc85d3e8e3c7477693532c000745aa60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":350},
            "size":{
              "width":140,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5355fc17327241e2a3acead3437dbb68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":350},
                "size":{
                  "width":140,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8782e6431a404abd92a966047a60e8f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":350},
            "size":{
              "width":83,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4833ab083ae44a28618aefd2ea8b006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":350},
                "size":{
                  "width":83,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4d11bd4fcd049f48bd9f18311044bfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":376},
            "size":{
              "width":140,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"983c6a6f120e424abc3dbdda933939d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":376},
                "size":{
                  "width":140,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2b25fed572f4171ae357f4e6912ef6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":372},
            "size":{
              "width":83,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"809d6fb9eb7a45caa99c1552973d5439",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":372},
                "size":{
                  "width":83,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4a7ad6e62c64542bb599de3eed8d13e",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":716,
              "y":300},
            "size":{
              "width":290,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ee682b114eb4943a7db6f7be646e1d7",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":290,
                  "height":31}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd298cf6d65a44669ce9f41aae213ca8",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":145,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1bd9a5189484cbbb4edcdb554da075f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":145,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u92.png"}},
{
                  "id":"faa169562d5541cbbf2dfb42af90bc49",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":145,
                      "y":0},
                    "size":{
                      "width":145,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09886f5c4b8444acb3f968579523c016",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":145,
                          "y":0},
                        "size":{
                          "width":145,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u94.png"}}]}]},
{
          "id":"ac0bbe5a76fb464f9975bec3d66158bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":973,
              "y":450},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d6f0fa9d60e4e598d36293e20a9efd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":973,
                  "y":450},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"171f6e1362304afaa8455d0e9f750730",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":752,
              "y":504},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecbba245484e465492ae784ea0360c1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":752,
                  "y":504},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u98.png"}},
{
          "id":"b98ac4da2581481fb1202253a5804fe3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":817,
              "y":519},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38d9856fd5b94fcaae7dc8cc0f99e86e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":817,
                  "y":519},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33d6d2103ab04eb8b426236b9a9d10f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":925},
            "size":{
              "width":178,
              "height":278}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b41aa6c6bc0a48739dd6aa9dbb767df7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":925},
                "size":{
                  "width":178,
                  "height":278}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u48.png"}},
{
          "id":"da8c748174da4234bcdbd4c63130f5cf",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":0},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"9de4a8a7440d478cb8e67e4c77f66b15",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 留言版 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"留言版.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "90770aef0ec0430cbeacacecaddca246":{
      "scriptId":"u0"},
    "7abedd662d194ecd9899163cbc39fde2":{
      "scriptId":"u1"},
    "848b3ea6905440e2ae4ee2723cf5596e":{
      "scriptId":"u2"},
    "65f0012225bb4930b5dde5a35d7d9546":{
      "scriptId":"u3"},
    "ab9647097e974f22a0397778a7f0e67d":{
      "scriptId":"u4"},
    "2ab6d5bc79064b48930dccb15b8c7bcd":{
      "scriptId":"u5"},
    "da9ab326c85b45cd91a5be270aaf1e78":{
      "scriptId":"u6"},
    "098f6692061a4f21bb82326c9d701ce3":{
      "scriptId":"u7"},
    "0a87e1103f7442edb3a851713de76ff9":{
      "scriptId":"u8"},
    "980ec942accc4c42976aaf3de115d01e":{
      "scriptId":"u9"},
    "9bb71bebd799460f89341f7f13793d4e":{
      "scriptId":"u10"},
    "129cc84db06946009a57f0806a95ca9f":{
      "scriptId":"u11"},
    "46f8dae0f8124583b388bc77089013d4":{
      "scriptId":"u12"},
    "06557629260643d182b293fe09c4e309":{
      "scriptId":"u13"},
    "4eacbbfec00848d0bb11fc0720adadd8":{
      "scriptId":"u14"},
    "102a58d7dbb04034afca3aa0969bedc6":{
      "scriptId":"u15"},
    "91a60a37b1b0467a8f12d372e2a20b2a":{
      "scriptId":"u16"},
    "ec57ff5282a34865b0c08a91d04a5c32":{
      "scriptId":"u17"},
    "fc2a08b60bb643789d6d60a83b6f363c":{
      "scriptId":"u18"},
    "87b6791916cc47eea5b0fdc7e3deab0a":{
      "scriptId":"u19"},
    "2d076e7bef144ecf9c03d38681490d98":{
      "scriptId":"u20"},
    "332d50a6ef5b47b99a99cbc33d7acde4":{
      "scriptId":"u21"},
    "c3859a13f95742dfa911bd286519c23e":{
      "scriptId":"u22"},
    "6f31e3bcae864169a399073126101ec7":{
      "scriptId":"u23"},
    "77bf7a9a02154eec8afc9367123aee4e":{
      "scriptId":"u24"},
    "8edd20794a9b48a39f303eda2ba8c2fa":{
      "scriptId":"u25"},
    "1c431f44ab9240b39ddee0e11ae9dd10":{
      "scriptId":"u26"},
    "db9ad850ad3249ebabe6dce8f5ef6c08":{
      "scriptId":"u27"},
    "93ab2e03d87648fba7de6180c542e874":{
      "scriptId":"u28"},
    "66b3b9ffe4534c64a1d9af0be0eaa2f2":{
      "scriptId":"u29"},
    "b8f3ed36562a4c3a81efb3bd77a40655":{
      "scriptId":"u30"},
    "53d124929b4b4333bd3e9dbfc8842c7e":{
      "scriptId":"u31"},
    "4dbb14ce29c84168a14aa6a55b510f32":{
      "scriptId":"u32"},
    "7f18535c79c9405c9ded58b39feba17e":{
      "scriptId":"u33"},
    "995fdea1ce68482ca27f1461e51b8a42":{
      "scriptId":"u34"},
    "070d94794fde497e8c8f1b654d3dac93":{
      "scriptId":"u35"},
    "afbb7fbb228a4eed95f65bf3ede43451":{
      "scriptId":"u36"},
    "8224cef397614f5ab6a45bbe511399ec":{
      "scriptId":"u37"},
    "bf05c4f7ce6d44ef9067d4743a099ee9":{
      "scriptId":"u38"},
    "88bf7358d2e349e5bd7bd9b96fa54500":{
      "scriptId":"u39"},
    "ed668f100e554afbad305b8b44c4d9cb":{
      "scriptId":"u40"},
    "f3038f9c4df44338bbb38a3bc35150e8":{
      "scriptId":"u41"},
    "6de2bdde18534e50aff0244bf9b65974":{
      "scriptId":"u42"},
    "1298bee229f74abcbadf8304142871f0":{
      "scriptId":"u43"},
    "16189265208140d08e77482d6041cd07":{
      "scriptId":"u44"},
    "868dc0cfa23e404588362faec76b5e56":{
      "scriptId":"u45"},
    "d80bac0b238b4791a8948364ef2661ef":{
      "scriptId":"u46"},
    "f64f965085ed4b21ab8e9fb8a00734ff":{
      "scriptId":"u47"},
    "08a1a5e25e1c4054aeb3af94cc39cdc0":{
      "scriptId":"u48"},
    "f87e8f8bce524e6b9990247e299f4939":{
      "scriptId":"u49"},
    "d434eb498ad7455190c9774bd1df3044":{
      "scriptId":"u50"},
    "210af42bd48e45b299f114534bdb6fd9":{
      "scriptId":"u51"},
    "5ddc9beb4b8d4c0f8f7041f0bbfc153c":{
      "scriptId":"u52"},
    "61eab2a085d143ebb73a39c80fd2be55":{
      "scriptId":"u53"},
    "c18b81ca753648e9a0c640d07acbb1a9":{
      "scriptId":"u54"},
    "52ffaf4536474738baa10e109550dc59":{
      "scriptId":"u55"},
    "b610716b3e1643a3a216433f95d74c31":{
      "scriptId":"u56"},
    "599f19cded7444a898f3409d239e613f":{
      "scriptId":"u57"},
    "05d9954f6edb4619a113914a458a6698":{
      "scriptId":"u58"},
    "c319687549f948519cd3f21fa78138c9":{
      "scriptId":"u59"},
    "50b3eb00cabf45a89518e030ea3e9db1":{
      "scriptId":"u60"},
    "f08fcfca19df4e10a6e7d41b7479d9b6":{
      "scriptId":"u61"},
    "1ce6f54f71554f58be44fc779339c1a8":{
      "scriptId":"u62"},
    "01be9003e4e540ab8a8f46b2a3f197d1":{
      "scriptId":"u63"},
    "64a726f55a6544289aa9da0d9863c7c9":{
      "scriptId":"u64"},
    "ca5477e777a34104b32e869bb7a0a0a5":{
      "scriptId":"u65"},
    "900bf12812ab4720aaa3da379e298342":{
      "scriptId":"u66"},
    "fe42a76ae03e4c5d8f4c1d285bc4bba5":{
      "scriptId":"u67"},
    "690d6071515f481d8845e75ad7efb2b4":{
      "scriptId":"u68"},
    "021b58e646404892a00c465f53515634":{
      "scriptId":"u69"},
    "9bb1478d1c504bf4ad24c5470c0860bf":{
      "scriptId":"u70"},
    "ff6f2a198d6a4dd6ada526619f7e82ad":{
      "scriptId":"u71"},
    "a63c59b8a7f44c408b8120188239e50b":{
      "scriptId":"u72"},
    "0fa1b54102e644e1a10aa978deb5c975":{
      "scriptId":"u73"},
    "deda7fef11414da7baf1a6e2b98fdd94":{
      "scriptId":"u74"},
    "4bd629569a6c4d90ab66797d79683c7a":{
      "scriptId":"u75"},
    "eaab1cb9e9684af39cb45a77c47796b7":{
      "scriptId":"u76"},
    "680f3d9996174cdcb5d9ad310c3b49fc":{
      "scriptId":"u77"},
    "3edd402d879f4b73864e85c8b7693b55":{
      "scriptId":"u78"},
    "5ca0b3fbf7a04490a68210f3e8e3637e":{
      "scriptId":"u79"},
    "a03d616bcdfe415b9857fe837850cf63":{
      "scriptId":"u80"},
    "1ae81996e97c4641a24ec9f13b9d78f3":{
      "scriptId":"u81"},
    "fc85d3e8e3c7477693532c000745aa60":{
      "scriptId":"u82"},
    "5355fc17327241e2a3acead3437dbb68":{
      "scriptId":"u83"},
    "8782e6431a404abd92a966047a60e8f9":{
      "scriptId":"u84"},
    "b4833ab083ae44a28618aefd2ea8b006":{
      "scriptId":"u85"},
    "a4d11bd4fcd049f48bd9f18311044bfb":{
      "scriptId":"u86"},
    "983c6a6f120e424abc3dbdda933939d8":{
      "scriptId":"u87"},
    "f2b25fed572f4171ae357f4e6912ef6f":{
      "scriptId":"u88"},
    "809d6fb9eb7a45caa99c1552973d5439":{
      "scriptId":"u89"},
    "d4a7ad6e62c64542bb599de3eed8d13e":{
      "scriptId":"u90"},
    "7ee682b114eb4943a7db6f7be646e1d7":{
      "scriptId":"u91"},
    "dd298cf6d65a44669ce9f41aae213ca8":{
      "scriptId":"u92"},
    "b1bd9a5189484cbbb4edcdb554da075f":{
      "scriptId":"u93"},
    "faa169562d5541cbbf2dfb42af90bc49":{
      "scriptId":"u94"},
    "09886f5c4b8444acb3f968579523c016":{
      "scriptId":"u95"},
    "ac0bbe5a76fb464f9975bec3d66158bd":{
      "scriptId":"u96"},
    "5d6f0fa9d60e4e598d36293e20a9efd5":{
      "scriptId":"u97"},
    "171f6e1362304afaa8455d0e9f750730":{
      "scriptId":"u98"},
    "ecbba245484e465492ae784ea0360c1f":{
      "scriptId":"u99"},
    "b98ac4da2581481fb1202253a5804fe3":{
      "scriptId":"u100"},
    "38d9856fd5b94fcaae7dc8cc0f99e86e":{
      "scriptId":"u101"},
    "33d6d2103ab04eb8b426236b9a9d10f5":{
      "scriptId":"u102"},
    "b41aa6c6bc0a48739dd6aa9dbb767df7":{
      "scriptId":"u103"},
    "da8c748174da4234bcdbd4c63130f5cf":{
      "scriptId":"u104"},
    "9de4a8a7440d478cb8e67e4c77f66b15":{
      "scriptId":"u105"}}});