$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1401969969363.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4ea3ec29c80b4d8ea8755963ef82dfed",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9f8b03df48fc4c2d90f38788ab9357f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009966,
              "opacity":1},
            "size":{
              "width":1350,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dac610ecbde46b693577cb1f32dd891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009966,
                  "opacity":1},
                "size":{
                  "width":1350,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品管理员 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品管理员.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"2400a1f738a9413590090fdf7e5a5a30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":140},
            "size":{
              "width":385,
              "height":320}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54aa5d18e6e64d15a4b054c102f55e4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":140},
                "size":{
                  "width":385,
                  "height":320}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u2.png"}},
{
          "id":"808ebf100fda42e69b3fee4a520b054a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":170},
            "size":{
              "width":340,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22a8c9d833af429aad08e1c4a6d0b909",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":170},
                "size":{
                  "width":340,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"04c2578dae1c4deb9b32e049cd7189db",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":225},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f2ac786c34314544bebfe054502538e3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":287.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a9368e54eaf145e6841a3eed39335254",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":349},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6ec6b4d51fca4d10b72a6b16c44af6c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":831,
              "y":230},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fe1ea87b1914983924e6aca4e1b000c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":831,
                  "y":230},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f201035880734bbe9211ffc670d794b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":832,
              "y":292},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"794e92e5e70a4c1089445bdc5edeb7c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":832,
                  "y":292},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e766997efd5c4e8999b01d07ea989b06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1036,
              "y":323},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b97cfdb38ad480e9c1ec3b728802a6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1036,
                  "y":323},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31d6c71840b94a11bb360e9a16dfe336",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 超级管理员 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"超级管理员.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8c96fb262a1e43819ae62cfc69104cde",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品管理员 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品管理员.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"06ab3671da8b4aadbdff15461c9a19b8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":930,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 订单管理员 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"订单管理员.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"07f91797f2714a6bac871a9ba533e3e0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1060,
              "y":509},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 用户管理员 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"用户管理员.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"14b371e593764cfeba05213fca21e1ec",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":509},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 综合管理员_广告管理 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"综合管理员_广告管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "9f8b03df48fc4c2d90f38788ab9357f8":{
      "scriptId":"u0"},
    "9dac610ecbde46b693577cb1f32dd891":{
      "scriptId":"u1"},
    "2400a1f738a9413590090fdf7e5a5a30":{
      "scriptId":"u2"},
    "54aa5d18e6e64d15a4b054c102f55e4f":{
      "scriptId":"u3"},
    "808ebf100fda42e69b3fee4a520b054a":{
      "scriptId":"u4"},
    "22a8c9d833af429aad08e1c4a6d0b909":{
      "scriptId":"u5"},
    "04c2578dae1c4deb9b32e049cd7189db":{
      "scriptId":"u6"},
    "f2ac786c34314544bebfe054502538e3":{
      "scriptId":"u7"},
    "a9368e54eaf145e6841a3eed39335254":{
      "scriptId":"u8"},
    "6ec6b4d51fca4d10b72a6b16c44af6c9":{
      "scriptId":"u9"},
    "3fe1ea87b1914983924e6aca4e1b000c":{
      "scriptId":"u10"},
    "f201035880734bbe9211ffc670d794b2":{
      "scriptId":"u11"},
    "794e92e5e70a4c1089445bdc5edeb7c3":{
      "scriptId":"u12"},
    "e766997efd5c4e8999b01d07ea989b06":{
      "scriptId":"u13"},
    "9b97cfdb38ad480e9c1ec3b728802a6b":{
      "scriptId":"u14"},
    "31d6c71840b94a11bb360e9a16dfe336":{
      "scriptId":"u15"},
    "8c96fb262a1e43819ae62cfc69104cde":{
      "scriptId":"u16"},
    "06ab3671da8b4aadbdff15461c9a19b8":{
      "scriptId":"u17"},
    "07f91797f2714a6bac871a9ba533e3e0":{
      "scriptId":"u18"},
    "14b371e593764cfeba05213fca21e1ec":{
      "scriptId":"u19"}}});