$axure.loadCurrentPage({
  "url":"个人中心-订单管理-商品评价.html",
  "generationDate":new Date(1402041964158.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8128ed8f5eb1497abba4e83123773c0b",
    "type":"Axure:Page",
    "name":"个人中心-订单管理-商品评价",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"99bfd1099295492693f6b1e802bde55c",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":289.5},
            "size":{
              "width":818,
              "height":211}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afa47b08e71443408c269bf76645589f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":121,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61507ac8cc604bdd949a38c80712a186",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":121,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u1.png"}},
{
              "id":"e0e37d96ed3948e7841d575495ba857f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":121,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4dec4e7a781489094b9c679f2b6002f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":121,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"Case 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"Open 个人中心-订单管理-单个订单 in New Window/Tab",
                          "target":{
                            "targetType":"page",
                            "url":"个人中心-订单管理-单个订单.html",
                            "includeVariables":true},
                          "linkType":"new"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u9.png"}},
{
              "id":"beb5697bad9c4654adee0a7deeabec8d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":76},
                "size":{
                  "width":121,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"385c3fa817f947a78824b73ee710c17d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":121,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u17.png"}},
{
              "id":"ceb792cbd3e840c8b264826051c5f46f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":121,
                  "y":0},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ed0cb3fc5cd4f90a7d14b0c742ef4fc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":121,
                      "y":0},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u3.png"}},
{
              "id":"97c8294f2dbf45b8920d447f3e7d523b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":121,
                  "y":30},
                "size":{
                  "width":108,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a73d4f91787548b7a9685bcbeb0155b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":121,
                      "y":30},
                    "size":{
                      "width":108,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u11.png"}},
{
              "id":"d2eabc8f4fc24725994a1c3d0f7ac495",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":121,
                  "y":76},
                "size":{
                  "width":108,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24c5f710d5d2433c838455e0cee5bcf3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":121,
                      "y":76},
                    "size":{
                      "width":108,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u19.png"}},
{
              "id":"6ecdb3cfde094bd3b6ced8358a926e2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":371,
                  "y":0},
                "size":{
                  "width":447,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f78f9138849444dbba455654817ecd4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":371,
                      "y":0},
                    "size":{
                      "width":447,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u7.png"}},
{
              "id":"2a0a17ca63964aa7ae717a81400c5a6e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":371,
                  "y":30},
                "size":{
                  "width":447,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70d491c08dc84e0291a9ec27ee98a04e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":371,
                      "y":30},
                    "size":{
                      "width":447,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u15.png"}},
{
              "id":"2e1e8e0c53e04ee7b995b37efb97d4d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":371,
                  "y":76},
                "size":{
                  "width":447,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d54832890d74e24805675f5ecfb983a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":371,
                      "y":76},
                    "size":{
                      "width":447,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u23.png"}},
{
              "id":"c599caba279943a1a9bb043f1627b3de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":121},
                "size":{
                  "width":121,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f76d205434bf4920864fe33b7e9788f0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":121},
                    "size":{
                      "width":121,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u17.png"}},
{
              "id":"a71aa967fc7246af85b30fc4ed99774a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":121,
                  "y":121},
                "size":{
                  "width":108,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7a8ad252118b4e3589a6eec4fed55458",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":121,
                      "y":121},
                    "size":{
                      "width":108,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u19.png"}},
{
              "id":"723c175379ca40daa25e43e47beb9c99",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":371,
                  "y":121},
                "size":{
                  "width":447,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97a1640fc0494bf0a1bf68539ebbf046",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":371,
                      "y":121},
                    "size":{
                      "width":447,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u23.png"}},
{
              "id":"8c68699ddd854cd1ad3bce1195a225cb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":166},
                "size":{
                  "width":121,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f98cb41244d4418bc28414cf873950f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":166},
                    "size":{
                      "width":121,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u33.png"}},
{
              "id":"3f768c9c4ba44fe88a2bb27866a4330e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":121,
                  "y":166},
                "size":{
                  "width":108,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"983d7b8462b64901b6b36aa0ec19d509",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":121,
                      "y":166},
                    "size":{
                      "width":108,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u35.png"}},
{
              "id":"69f950ed53df4704a8037140d139ab53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":371,
                  "y":166},
                "size":{
                  "width":447,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e4c0d60e908f4c589f28b416e6a391a9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":371,
                      "y":166},
                    "size":{
                      "width":447,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u39.png"}},
{
              "id":"45127ad85ee145c9ad8cdb7bae5bd0a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":229,
                  "y":0},
                "size":{
                  "width":142,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"282daa6e2a7b4932b0dde09523d34722",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":229,
                      "y":0},
                    "size":{
                      "width":142,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u5.png"}},
{
              "id":"ed82f4f8dfc2401592e72d2a9f32e392",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":229,
                  "y":30},
                "size":{
                  "width":142,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d272813a51947c8b284abd2dad657a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":229,
                      "y":30},
                    "size":{
                      "width":142,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u13.png"}},
{
              "id":"1547d824a5054411871d0d95557b79ce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":229,
                  "y":76},
                "size":{
                  "width":142,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12d52c322d9c4ef1868b2758d334aa92",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":229,
                      "y":76},
                    "size":{
                      "width":142,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u21.png"}},
{
              "id":"5a4dd89491294838bc79267b83f24f89",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":229,
                  "y":121},
                "size":{
                  "width":142,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"01b6407e5f064ef49de610e2a6974d3a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":229,
                      "y":121},
                    "size":{
                      "width":142,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u21.png"}},
{
              "id":"e5930ec239f14409bcded19dadb36982",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":229,
                  "y":166},
                "size":{
                  "width":142,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f2f2766c9d346858eae698e81c71832",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":229,
                      "y":166},
                    "size":{
                      "width":142,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理-商品评价/u37.png"}}]},
{
          "id":"7a0da00c82bc45fcbcabc95893cc9820",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":532.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5177a81cfe9448a9b012af428255b040",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":1000,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"622758a7ce514347951839036752fe9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":1000,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"dc0831648a1a4ef39ce0eea1bdcb0628",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"780f45a940654aa2bd1e68bb2a73f996",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f1510ee79d3c4ed4af4e35ffa8b9756e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"14f426de409c4654a642e0c873a04855",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e61f734548de4f568dad3a6471cff232",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":7},
            "size":{
              "width":90,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf92f0e2bfb344f7b13ecc25929c4c8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":7},
                "size":{
                  "width":90,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18ce43863e234c5eac4025b21a94da86",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":0},
            "size":{
              "width":100,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"5adf3264b209464d88093f10b19ff5df",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"81a99c457a8348df8b14f75b5386bb7f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":200},
            "size":{
              "width":169,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dabc1d1d2f48471296b26536a8e7ea21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":169,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-个人信息/u48.png"}},
{
          "id":"813b7b06ed8d43a6af3a8030f9751f4a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":-10,
              "y":632},
            "size":{
              "width":1000,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"829d0142de1e4343b9967de1a70a0fdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":-10,
                  "y":632},
                "size":{
                  "width":1000,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u46.png"}},
{
          "id":"b24efd850e624aa984fc2ad39e6b2f3d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心-个人信息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c59fe0dbef6241b8a6f307f11886d7f7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":430},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in New Window/Tab",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"3b065ee346e44efb8d8177cfb690850e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":480},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in New Window/Tab",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"f9d999d90f034a358b711d344d3fb53d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":530},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心-订单管理 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-订单管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"79f09e97516e4769a7d666ee9d09c814",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":580},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"00b87edd88e447bdae12b1d39d07ef9c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":420},
            "size":{
              "width":77,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"50c838f815804993b83845c27c428dee",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":377},
            "size":{
              "width":77,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9d9231e0d13c43c68fed17825979ffad",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":330},
            "size":{
              "width":77,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6a1f3af7164f4003a85fdfa4ae86175a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":190,
              "y":234},
            "size":{
              "width":197,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb6e490d14b24ee9bfe6162ac243df12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":190,
                  "y":234},
                "size":{
                  "width":197,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70570daeec4140ebbfcd43dc4400036a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":484,
              "y":234},
            "size":{
              "width":179,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a456cb4b4c24075bc201875cdf73453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":484,
                  "y":234},
                "size":{
                  "width":179,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a66f575bf693407dbc936ffcf167564e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":330},
            "size":{
              "width":330,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"76be4fc2f9a5410bb36773e877bf7712",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":377},
            "size":{
              "width":330,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"357b4a1531f94ef88b49622250101993",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":420},
            "size":{
              "width":330,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4e37892ddde847b9a8594fd8dcd71f03",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":335},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a10cd6cbd2234649810428c8a0f907a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":335},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f12f5db66e734054a6c03c9698465bb7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":350},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89618413e5894f24be36044ccc60f231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":350},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7a23652c8e8240e1ac4a058dd208ad62",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":320},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"540bceafd9fe472794d5e453d569fb82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":320},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "99bfd1099295492693f6b1e802bde55c":{
      "scriptId":"u0"},
    "afa47b08e71443408c269bf76645589f":{
      "scriptId":"u1"},
    "61507ac8cc604bdd949a38c80712a186":{
      "scriptId":"u2"},
    "ceb792cbd3e840c8b264826051c5f46f":{
      "scriptId":"u3"},
    "4ed0cb3fc5cd4f90a7d14b0c742ef4fc":{
      "scriptId":"u4"},
    "45127ad85ee145c9ad8cdb7bae5bd0a9":{
      "scriptId":"u5"},
    "282daa6e2a7b4932b0dde09523d34722":{
      "scriptId":"u6"},
    "6ecdb3cfde094bd3b6ced8358a926e2a":{
      "scriptId":"u7"},
    "1f78f9138849444dbba455654817ecd4":{
      "scriptId":"u8"},
    "e0e37d96ed3948e7841d575495ba857f":{
      "scriptId":"u9"},
    "b4dec4e7a781489094b9c679f2b6002f":{
      "scriptId":"u10"},
    "97c8294f2dbf45b8920d447f3e7d523b":{
      "scriptId":"u11"},
    "a73d4f91787548b7a9685bcbeb0155b9":{
      "scriptId":"u12"},
    "ed82f4f8dfc2401592e72d2a9f32e392":{
      "scriptId":"u13"},
    "5d272813a51947c8b284abd2dad657a5":{
      "scriptId":"u14"},
    "2a0a17ca63964aa7ae717a81400c5a6e":{
      "scriptId":"u15"},
    "70d491c08dc84e0291a9ec27ee98a04e":{
      "scriptId":"u16"},
    "beb5697bad9c4654adee0a7deeabec8d":{
      "scriptId":"u17"},
    "385c3fa817f947a78824b73ee710c17d":{
      "scriptId":"u18"},
    "d2eabc8f4fc24725994a1c3d0f7ac495":{
      "scriptId":"u19"},
    "24c5f710d5d2433c838455e0cee5bcf3":{
      "scriptId":"u20"},
    "1547d824a5054411871d0d95557b79ce":{
      "scriptId":"u21"},
    "12d52c322d9c4ef1868b2758d334aa92":{
      "scriptId":"u22"},
    "2e1e8e0c53e04ee7b995b37efb97d4d6":{
      "scriptId":"u23"},
    "6d54832890d74e24805675f5ecfb983a":{
      "scriptId":"u24"},
    "c599caba279943a1a9bb043f1627b3de":{
      "scriptId":"u25"},
    "f76d205434bf4920864fe33b7e9788f0":{
      "scriptId":"u26"},
    "a71aa967fc7246af85b30fc4ed99774a":{
      "scriptId":"u27"},
    "7a8ad252118b4e3589a6eec4fed55458":{
      "scriptId":"u28"},
    "5a4dd89491294838bc79267b83f24f89":{
      "scriptId":"u29"},
    "01b6407e5f064ef49de610e2a6974d3a":{
      "scriptId":"u30"},
    "723c175379ca40daa25e43e47beb9c99":{
      "scriptId":"u31"},
    "97a1640fc0494bf0a1bf68539ebbf046":{
      "scriptId":"u32"},
    "8c68699ddd854cd1ad3bce1195a225cb":{
      "scriptId":"u33"},
    "1f98cb41244d4418bc28414cf873950f":{
      "scriptId":"u34"},
    "3f768c9c4ba44fe88a2bb27866a4330e":{
      "scriptId":"u35"},
    "983d7b8462b64901b6b36aa0ec19d509":{
      "scriptId":"u36"},
    "e5930ec239f14409bcded19dadb36982":{
      "scriptId":"u37"},
    "2f2f2766c9d346858eae698e81c71832":{
      "scriptId":"u38"},
    "69f950ed53df4704a8037140d139ab53":{
      "scriptId":"u39"},
    "e4c0d60e908f4c589f28b416e6a391a9":{
      "scriptId":"u40"},
    "7a0da00c82bc45fcbcabc95893cc9820":{
      "scriptId":"u41"},
    "5177a81cfe9448a9b012af428255b040":{
      "scriptId":"u42"},
    "622758a7ce514347951839036752fe9c":{
      "scriptId":"u43"},
    "dc0831648a1a4ef39ce0eea1bdcb0628":{
      "scriptId":"u44"},
    "780f45a940654aa2bd1e68bb2a73f996":{
      "scriptId":"u45"},
    "f1510ee79d3c4ed4af4e35ffa8b9756e":{
      "scriptId":"u46"},
    "14f426de409c4654a642e0c873a04855":{
      "scriptId":"u47"},
    "e61f734548de4f568dad3a6471cff232":{
      "scriptId":"u48"},
    "cf92f0e2bfb344f7b13ecc25929c4c8b":{
      "scriptId":"u49"},
    "18ce43863e234c5eac4025b21a94da86":{
      "scriptId":"u50"},
    "5adf3264b209464d88093f10b19ff5df":{
      "scriptId":"u51"},
    "81a99c457a8348df8b14f75b5386bb7f":{
      "scriptId":"u52"},
    "dabc1d1d2f48471296b26536a8e7ea21":{
      "scriptId":"u53"},
    "813b7b06ed8d43a6af3a8030f9751f4a":{
      "scriptId":"u54"},
    "829d0142de1e4343b9967de1a70a0fdd":{
      "scriptId":"u55"},
    "b24efd850e624aa984fc2ad39e6b2f3d":{
      "scriptId":"u56"},
    "c59fe0dbef6241b8a6f307f11886d7f7":{
      "scriptId":"u57"},
    "3b065ee346e44efb8d8177cfb690850e":{
      "scriptId":"u58"},
    "f9d999d90f034a358b711d344d3fb53d":{
      "scriptId":"u59"},
    "79f09e97516e4769a7d666ee9d09c814":{
      "scriptId":"u60"},
    "00b87edd88e447bdae12b1d39d07ef9c":{
      "scriptId":"u61"},
    "50c838f815804993b83845c27c428dee":{
      "scriptId":"u62"},
    "9d9231e0d13c43c68fed17825979ffad":{
      "scriptId":"u63"},
    "6a1f3af7164f4003a85fdfa4ae86175a":{
      "scriptId":"u64"},
    "bb6e490d14b24ee9bfe6162ac243df12":{
      "scriptId":"u65"},
    "70570daeec4140ebbfcd43dc4400036a":{
      "scriptId":"u66"},
    "5a456cb4b4c24075bc201875cdf73453":{
      "scriptId":"u67"},
    "a66f575bf693407dbc936ffcf167564e":{
      "scriptId":"u68"},
    "76be4fc2f9a5410bb36773e877bf7712":{
      "scriptId":"u69"},
    "357b4a1531f94ef88b49622250101993":{
      "scriptId":"u70"},
    "4e37892ddde847b9a8594fd8dcd71f03":{
      "scriptId":"u71"},
    "a10cd6cbd2234649810428c8a0f907a3":{
      "scriptId":"u72"},
    "f12f5db66e734054a6c03c9698465bb7":{
      "scriptId":"u73"},
    "89618413e5894f24be36044ccc60f231":{
      "scriptId":"u74"},
    "7a23652c8e8240e1ac4a058dd208ad62":{
      "scriptId":"u75"},
    "540bceafd9fe472794d5e453d569fb82":{
      "scriptId":"u76"}}});