$axure.loadCurrentPage({
  "url":"提交订单.html",
  "generationDate":new Date(1402041962593.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cc1ef895436941f2b23d4ceccdfda58e",
    "type":"Axure:Page",
    "name":"提交订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0f738c9d6cd24b3dbe94a1bfbe0fe0ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":480},
            "size":{
              "width":1000,
              "height":401}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52e0dfdc723f4e5cb36c428c63ac8f79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":480},
                "size":{
                  "width":1000,
                  "height":401}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交订单/u0.png"}},
{
          "id":"a4f96351205c4f0b8adb8292c9990a8d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":526},
            "size":{
              "width":957,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购物车/u6_line.png"}},
{
          "id":"798bb1c451904aabbec63bfb725eff22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":694,
              "y":801},
            "size":{
              "width":79,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cd3b846694f43f280d501cacbd42676",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":694,
                  "y":801},
                "size":{
                  "width":79,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5aa34608101d4e43a1f1c043a3a332b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":801},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baa6495e8ae1463d99bde84173ea34f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":801},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4de26752a9dc414d88e00d466ef79da0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":29,
              "y":480},
            "size":{
              "width":131,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd2a9e82686547d8b1a0cf54b35de426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":29,
                  "y":480},
                "size":{
                  "width":131,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"faaa6f17fd7542458941a1f073c5ee6d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":550},
            "size":{
              "width":926,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeb13150c82a4d7ea364e92e1a67397d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":509,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"008bf006edcf4fbab2e8740fe558b74c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":509,
                      "height":57},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u10.png"}},
{
              "id":"7c8c804b1c7d48f3bc6d3fa50fb08c07",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":509,
                  "y":0},
                "size":{
                  "width":155,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75895e713a9e46cbb113201ec0dbe549",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":509,
                      "y":0},
                    "size":{
                      "width":155,
                      "height":57},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u12.png"}},
{
              "id":"489c25dfb4be405f80af38c6c5d8ecec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":664,
                  "y":0},
                "size":{
                  "width":127,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7276d320ef5c4d51a1f4495c52500e3e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":664,
                      "y":0},
                    "size":{
                      "width":127,
                      "height":57},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u14.png"}},
{
              "id":"1ccea9305ff5450f865553726024159d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":791,
                  "y":0},
                "size":{
                  "width":135,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed32c8c56c514f14afb6141fe76c66a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":791,
                      "y":0},
                    "size":{
                      "width":135,
                      "height":57},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u16.png"}}]},
{
          "id":"50624638de824ea69349f10effba607e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":652},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fbfa4687e6a40c0925beeab36b60dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":652},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"fe752305e2174898b935fbc3fe6cfa60",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":568},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbf28c98e1ee42d1894dbc739e43e5a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":568},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4e91475556284eaab2c1d691ed67bccb",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":617},
            "size":{
              "width":933,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"098b39d7e38a4d52a6fc6f96442c03ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":61,
                  "y":0},
                "size":{
                  "width":456,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1873637385e941df800f95d4e019ffa2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":61,
                      "y":0},
                    "size":{
                      "width":456,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u25.png"}},
{
              "id":"a7f8a42bb0644c3e86923f43e2389792",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":791,
                  "y":0},
                "size":{
                  "width":142,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e4114cd9bc64990ac312f722318fde9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":791,
                      "y":0},
                    "size":{
                      "width":142,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u31.png"}},
{
              "id":"a5e8250e20cd4d1dae90643f9c5aa57d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":666,
                  "y":0},
                "size":{
                  "width":125,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9dd4e6cc637b42da9ac7f146cb48fc6a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":666,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u39.png"}},
{
              "id":"982b9a0c6d31484e835b7ec4fd700c0e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":517,
                  "y":0},
                "size":{
                  "width":149,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c25e4ee3f0342fd96bf68e0267c60a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":517,
                      "y":0},
                    "size":{
                      "width":149,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u27.png"}},
{
              "id":"a6f3872fd1914147b05020f6f14cddd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":61,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15f56df9228b458fbe050be8763c3fe8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":61,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u23.png"}},
{
              "id":"8dee0648fb1f48568e04efce2f901702",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":77},
                "size":{
                  "width":61,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d4a16c64719d458db749b77a8d840be4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":77},
                    "size":{
                      "width":61,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u33.png"}},
{
              "id":"6a9a6f3679284730a7777b6acc0c6d44",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":61,
                  "y":77},
                "size":{
                  "width":456,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b783f9749f645dba5cf2cecb70347c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":61,
                      "y":77},
                    "size":{
                      "width":456,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u35.png"}},
{
              "id":"254b3d3623df421ba394fae46d4c55e9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":517,
                  "y":77},
                "size":{
                  "width":149,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90cce3243d4b4eb486d23f0179d75d39",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":517,
                      "y":77},
                    "size":{
                      "width":149,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u37.png"}},
{
              "id":"febcbe046a654e0989223f245f19bf6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":666,
                  "y":77},
                "size":{
                  "width":125,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d890df9137a04f1fa59f8813b05878a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":666,
                      "y":77},
                    "size":{
                      "width":125,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u51.png"}},
{
              "id":"308eb841e03343f3bc6af0cfbfe15ab2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":791,
                  "y":77},
                "size":{
                  "width":142,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"28782eb0ac3f4447a037b95bf8be0368",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":791,
                      "y":77},
                    "size":{
                      "width":142,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提交订单/u41.png"}}]},
{
          "id":"d6c7cdc34e9a40dcbfbc950b23377801",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":597},
            "size":{
              "width":947,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购物车/u55_line.png"}},
{
          "id":"119fb9f19eaf44859c69e4c49d32f843",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":648},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"991d0342d78643649d8ea8ca322bd70a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":648},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"8dbc77db95694868be70e012585f592e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":729},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0721b168e6ba4fc78f1d89528f6d47c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":729},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"07c64b383a32484ebf6ddf95201edf80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":1000,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc34dedd40e54a4eb89dfac3f66c8b4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":1000,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"42516eed59ce4adfa874a30c69f35c9a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"3bd9f490a2624040beb3d8a0b8e264a3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"67ae9e1a803a499eb2f89431f97d2dcd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"cf083dca2cde49c5aef665877b2c161a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5b8200f2a5ce403b92ba9c4618d89d6c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":836},
            "size":{
              "width":71,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a430c3263c3b48be82839fba25af5e4e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":836},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心-订单管理 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-订单管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8ad7eef2f554436f8f47ba18ffb7a558",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":7},
            "size":{
              "width":90,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edc305c166754959b4a9efaa2bc38d39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":7},
                "size":{
                  "width":90,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff409af58ca34c219b1d5aef349b4614",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":0},
            "size":{
              "width":100,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"443cf685648b4034ba266e7c85651c8e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":0,
              "y":891},
            "size":{
              "width":1000,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e09a5f74ae54ce8bd46b1554ed519ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":0,
                  "y":891},
                "size":{
                  "width":1000,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u46.png"}},
{
          "id":"bd83262f855544f29a446b2d196a7679",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c5e82a982eaf47f380ff4ebce1b5cbf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":20,
              "y":270},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cc6feb6987e40b69b2217745ac2cf11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":20,
                  "y":270},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2c4013858ed46af9b191b746b977d24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":7,
              "y":220},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7392ff7810364eb690a7d71d03d16945",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":7,
                  "y":220},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bca96575b53473f892d97986773163c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":389,
              "y":220},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d617c830a6c49f789429e2ffb9665da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":389,
                  "y":220},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e33923e413ec4bbc9e4769a7b2433759",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":695,
              "y":782},
            "size":{
              "width":40,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"422ed120480b42f5aafd89a775ba5704",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":695,
                  "y":782},
                "size":{
                  "width":40,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae93d2663d284aba8f53c6a6781364b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":831,
              "y":782},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a2310826d414510aad8fc6f1f3fc618",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":831,
                  "y":782},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"128d9b3da9d648b9b3ade6dd16b731de",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":475,
              "y":270},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "0f738c9d6cd24b3dbe94a1bfbe0fe0ed":{
      "scriptId":"u0"},
    "52e0dfdc723f4e5cb36c428c63ac8f79":{
      "scriptId":"u1"},
    "a4f96351205c4f0b8adb8292c9990a8d":{
      "scriptId":"u2"},
    "798bb1c451904aabbec63bfb725eff22":{
      "scriptId":"u3"},
    "4cd3b846694f43f280d501cacbd42676":{
      "scriptId":"u4"},
    "5aa34608101d4e43a1f1c043a3a332b7":{
      "scriptId":"u5"},
    "baa6495e8ae1463d99bde84173ea34f9":{
      "scriptId":"u6"},
    "4de26752a9dc414d88e00d466ef79da0":{
      "scriptId":"u7"},
    "cd2a9e82686547d8b1a0cf54b35de426":{
      "scriptId":"u8"},
    "faaa6f17fd7542458941a1f073c5ee6d":{
      "scriptId":"u9"},
    "eeb13150c82a4d7ea364e92e1a67397d":{
      "scriptId":"u10"},
    "008bf006edcf4fbab2e8740fe558b74c":{
      "scriptId":"u11"},
    "7c8c804b1c7d48f3bc6d3fa50fb08c07":{
      "scriptId":"u12"},
    "75895e713a9e46cbb113201ec0dbe549":{
      "scriptId":"u13"},
    "489c25dfb4be405f80af38c6c5d8ecec":{
      "scriptId":"u14"},
    "7276d320ef5c4d51a1f4495c52500e3e":{
      "scriptId":"u15"},
    "1ccea9305ff5450f865553726024159d":{
      "scriptId":"u16"},
    "ed32c8c56c514f14afb6141fe76c66a8":{
      "scriptId":"u17"},
    "50624638de824ea69349f10effba607e":{
      "scriptId":"u18"},
    "0fbfa4687e6a40c0925beeab36b60dac":{
      "scriptId":"u19"},
    "fe752305e2174898b935fbc3fe6cfa60":{
      "scriptId":"u20"},
    "bbf28c98e1ee42d1894dbc739e43e5a7":{
      "scriptId":"u21"},
    "4e91475556284eaab2c1d691ed67bccb":{
      "scriptId":"u22"},
    "a6f3872fd1914147b05020f6f14cddd8":{
      "scriptId":"u23"},
    "15f56df9228b458fbe050be8763c3fe8":{
      "scriptId":"u24"},
    "098b39d7e38a4d52a6fc6f96442c03ff":{
      "scriptId":"u25"},
    "1873637385e941df800f95d4e019ffa2":{
      "scriptId":"u26"},
    "982b9a0c6d31484e835b7ec4fd700c0e":{
      "scriptId":"u27"},
    "1c25e4ee3f0342fd96bf68e0267c60a2":{
      "scriptId":"u28"},
    "a5e8250e20cd4d1dae90643f9c5aa57d":{
      "scriptId":"u29"},
    "9dd4e6cc637b42da9ac7f146cb48fc6a":{
      "scriptId":"u30"},
    "a7f8a42bb0644c3e86923f43e2389792":{
      "scriptId":"u31"},
    "1e4114cd9bc64990ac312f722318fde9":{
      "scriptId":"u32"},
    "8dee0648fb1f48568e04efce2f901702":{
      "scriptId":"u33"},
    "d4a16c64719d458db749b77a8d840be4":{
      "scriptId":"u34"},
    "6a9a6f3679284730a7777b6acc0c6d44":{
      "scriptId":"u35"},
    "8b783f9749f645dba5cf2cecb70347c4":{
      "scriptId":"u36"},
    "254b3d3623df421ba394fae46d4c55e9":{
      "scriptId":"u37"},
    "90cce3243d4b4eb486d23f0179d75d39":{
      "scriptId":"u38"},
    "febcbe046a654e0989223f245f19bf6b":{
      "scriptId":"u39"},
    "d890df9137a04f1fa59f8813b05878a2":{
      "scriptId":"u40"},
    "308eb841e03343f3bc6af0cfbfe15ab2":{
      "scriptId":"u41"},
    "28782eb0ac3f4447a037b95bf8be0368":{
      "scriptId":"u42"},
    "d6c7cdc34e9a40dcbfbc950b23377801":{
      "scriptId":"u43"},
    "119fb9f19eaf44859c69e4c49d32f843":{
      "scriptId":"u44"},
    "991d0342d78643649d8ea8ca322bd70a":{
      "scriptId":"u45"},
    "8dbc77db95694868be70e012585f592e":{
      "scriptId":"u46"},
    "0721b168e6ba4fc78f1d89528f6d47c9":{
      "scriptId":"u47"},
    "07c64b383a32484ebf6ddf95201edf80":{
      "scriptId":"u48"},
    "dc34dedd40e54a4eb89dfac3f66c8b4f":{
      "scriptId":"u49"},
    "42516eed59ce4adfa874a30c69f35c9a":{
      "scriptId":"u50"},
    "3bd9f490a2624040beb3d8a0b8e264a3":{
      "scriptId":"u51"},
    "67ae9e1a803a499eb2f89431f97d2dcd":{
      "scriptId":"u52"},
    "cf083dca2cde49c5aef665877b2c161a":{
      "scriptId":"u53"},
    "5b8200f2a5ce403b92ba9c4618d89d6c":{
      "scriptId":"u54"},
    "a430c3263c3b48be82839fba25af5e4e":{
      "scriptId":"u55"},
    "8ad7eef2f554436f8f47ba18ffb7a558":{
      "scriptId":"u56"},
    "edc305c166754959b4a9efaa2bc38d39":{
      "scriptId":"u57"},
    "ff409af58ca34c219b1d5aef349b4614":{
      "scriptId":"u58"},
    "443cf685648b4034ba266e7c85651c8e":{
      "scriptId":"u59"},
    "3e09a5f74ae54ce8bd46b1554ed519ff":{
      "scriptId":"u60"},
    "bd83262f855544f29a446b2d196a7679":{
      "scriptId":"u61"},
    "c5e82a982eaf47f380ff4ebce1b5cbf1":{
      "scriptId":"u62"},
    "5cc6feb6987e40b69b2217745ac2cf11":{
      "scriptId":"u63"},
    "a2c4013858ed46af9b191b746b977d24":{
      "scriptId":"u64"},
    "7392ff7810364eb690a7d71d03d16945":{
      "scriptId":"u65"},
    "0bca96575b53473f892d97986773163c":{
      "scriptId":"u66"},
    "3d617c830a6c49f789429e2ffb9665da":{
      "scriptId":"u67"},
    "e33923e413ec4bbc9e4769a7b2433759":{
      "scriptId":"u68"},
    "422ed120480b42f5aafd89a775ba5704":{
      "scriptId":"u69"},
    "ae93d2663d284aba8f53c6a6781364b9":{
      "scriptId":"u70"},
    "2a2310826d414510aad8fc6f1f3fc618":{
      "scriptId":"u71"},
    "128d9b3da9d648b9b3ade6dd16b731de":{
      "scriptId":"u72"}}});