$axure.loadCurrentPage({
  "url":"个人中心-订单管理.html",
  "generationDate":new Date(1402041963385.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"677a91f072104014845774fe478e91b8",
    "type":"Axure:Page",
    "name":"个人中心-订单管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f8a4d27fb5514f468b98d11922de3c81",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":260},
            "size":{
              "width":771,
              "height":211}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f401ff710a1447f3bd159b42b0d59e53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74eea0a9fac3471eb6de8e2ffce73cd1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u1.png"}},
{
              "id":"032b46c109c14a61afced8874ab8e2d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":126,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d194c14d4e624b7e84b8dacdd15b4ad5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"Case 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"Open 个人中心-订单管理-单个订单 in New Window/Tab",
                          "target":{
                            "targetType":"page",
                            "url":"个人中心-订单管理-单个订单.html",
                            "includeVariables":true},
                          "linkType":"new"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/个人中心-订单管理/u11.png"}},
{
              "id":"d5ef75e8d13146c8a8217503f92a1838",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":76},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8027d2bf11214fbcb61375789a5dce3a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u21.png"}},
{
              "id":"65251419b3824deda5208bed6923bb14",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":0},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"044eec3f6440446e9e66b5457b3961b6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":0},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u1.png"}},
{
              "id":"a176bfeb414043b183bc06f8abbc5a66",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":30},
                "size":{
                  "width":126,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"17f1152afb1e49a68aa7b05a6ca7e5f2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u11.png"}},
{
              "id":"e176223f4c714b20b6d79428a3cb3edf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":76},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"08bac5b10c954150a191cdd4e1d5e14b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":76},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u21.png"}},
{
              "id":"e72fe13b40a4430db798377b4dda2b82",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":252,
                  "y":0},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"46b61e6a64df4ae9b8f65f7df6a32f4e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":252,
                      "y":0},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u1.png"}},
{
              "id":"f4a7732919bc48bc88762758f9881bf3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":252,
                  "y":30},
                "size":{
                  "width":126,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5e7a1d2102dd4685997f149580ad62a9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":252,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u11.png"}},
{
              "id":"433a81e14cfd44abbdf26ad16edc3e2d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":252,
                  "y":76},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d51b08eb78914cb6b2955077570db51f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":252,
                      "y":76},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u21.png"}},
{
              "id":"512a3a1b56ae455fa85ff660fdc70e32",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":0},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4d605ee3b4ca4fdebb5362677bdd48d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":0},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u1.png"}},
{
              "id":"902ab1b3dcda4914b267e661ce9bc604",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":30},
                "size":{
                  "width":126,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f5030c2f7854475b9a5cc1248ec5cda",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u11.png"}},
{
              "id":"64e17d5d784244789670dac642dcaac1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":76},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac64da514a5a45d1ac241a494beeeb57",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":76},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u21.png"}},
{
              "id":"25efaf53a25249c9b1b75d30445aa6ce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":0},
                "size":{
                  "width":267,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f7f2d29b6aed4e499642a8b25ebcb214",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":0},
                    "size":{
                      "width":267,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u9.png"}},
{
              "id":"6bf6357ed7ac499784e3627b6013cfe8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":30},
                "size":{
                  "width":267,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c93ef6aea903440d83826235d1382b38",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":30},
                    "size":{
                      "width":267,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u19.png"}},
{
              "id":"7b321d6bffcf481d954762dad054039d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":76},
                "size":{
                  "width":267,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1cce5af450f44befaebc89895fa8ec31",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":76},
                    "size":{
                      "width":267,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u29.png"}},
{
              "id":"63273ee7612e42049c85618f16b9ea73",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":121},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"295d1a68244c42b7b7190660fa2a9c78",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":121},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u21.png"}},
{
              "id":"c1b628f30f254c2cb12dd794114b4093",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":121},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9414c7bebc784c1bbb4ae3a04ff3333b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":121},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u21.png"}},
{
              "id":"4e1127265fe8473f8a44b945e97c2e03",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":252,
                  "y":121},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e5d26c6a6b1f4e1f916b4327e1758d90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":252,
                      "y":121},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u21.png"}},
{
              "id":"783939637bc74e4a840882d372d92824",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":121},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"52304a1c65b8437ca5d45c54e9956499",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":121},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u21.png"}},
{
              "id":"944dfccb0f9e4841a99a623c3366efa8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":121},
                "size":{
                  "width":267,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2c8a63fdc9749ec8547277e111aae5a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":121},
                    "size":{
                      "width":267,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u29.png"}},
{
              "id":"b204d2ddbde0455fb1b625d1edd5d40d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":166},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c98776da7b7641e7ac4e178179f328d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":166},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u41.png"}},
{
              "id":"cee47f7beb684cf6b866428fd813089a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":166},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"be914053ac7149a58c5206a2668e2a9b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":166},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u41.png"}},
{
              "id":"edf10e537df242f3b935a2f8bbe81f25",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":252,
                  "y":166},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ecb90bda3bd24844960ebd4162719e34",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":252,
                      "y":166},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u41.png"}},
{
              "id":"42454bbbd12d4fd086704a7ec18d1b77",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":166},
                "size":{
                  "width":126,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f6dd7a408eaa41b6b0bd606a5e6e4ce0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":166},
                    "size":{
                      "width":126,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u41.png"}},
{
              "id":"35719baf23ab4a6f93bc9d2755498cdd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":166},
                "size":{
                  "width":267,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e0297fcc6ff462a995d336da8ed4311",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":166},
                    "size":{
                      "width":267,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-订单管理/u49.png"}}]},
{
          "id":"e15fd5e1127a493abdb66c6983e3488e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":300},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a4346c8800d6472e801aec318da41709",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":345},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c7f0e57f48724336939bac6bde8e065e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":390},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3831e118a76e4d338e920b5be824cc70",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":390},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"74f09add1fc44cc19fea454a49ccb679",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":434},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"36ade854e8f74ad590c0c3c41c5130ed",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":220},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d3dad0407ca43da8dbeb52464cf6435",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":179,
                  "y":220},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"beae6232a3be4f3ca6a06cd8587b4293",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":220},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c16bad742ab4cbb847f1247b741f03b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":220},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"403fb83e982c42aab7e2723cbc0d09db",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":530},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f48a270c79204eb182666b78999f8b78",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":530},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6d880040cb4c4b60ad434b744076d57c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":484,
              "y":534},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cd9fbf1bb37495dbc7f27aea4ee6859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":484,
                  "y":534},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42ccc9cb0413489bb08ea513b9ca1973",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":1000,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8fb1992d3df4000b9c938643bdc5f62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":1000,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"bb1355a4c8134eb7b18bb77e582fef98",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"98373ac741194346bd1d5af9d11bad69",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"557b0275b43e46898a8fb121ea76e82b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"bb9ae8e92f914d8396a9d0a8beb09234",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f7d553fbf0b544f7889561f8e4def9d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":7},
            "size":{
              "width":90,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"606ec71b4faa4983924cf28796b5ca02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":7},
                "size":{
                  "width":90,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d82c196aac1d4e34830a059c8d92936d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":0},
            "size":{
              "width":100,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"a6166958c40e46b2b2b62fbde06a72db",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"33b6432cd22a4eb09178d31ba8f592af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":200},
            "size":{
              "width":169,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62fa254a8fc741a3ab17637afd1cbee1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":169,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-个人信息/u48.png"}},
{
          "id":"17ed49a17b444f06a96629cb93363037",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":-10,
              "y":632},
            "size":{
              "width":1000,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"447b08b487eb46959cfc9cd8118de244",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":-10,
                  "y":632},
                "size":{
                  "width":1000,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u46.png"}},
{
          "id":"355ec3be03e3433f960d55e13e63fca8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心-个人信息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"36c57e11d5174976a29dfe68d35cd58b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":430},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in New Window/Tab",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"f8ea728ea35841f7b94e9da19e6cdcca",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":480},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in New Window/Tab",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"9abb918fbb444159808ca99851484f2b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":530},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心-订单管理 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-订单管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"416d08d47e3c4790ad3bd664f0e08d85",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":580},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"cbb18aba65a14a1d9c0f0f1e89404908",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":345},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "f8a4d27fb5514f468b98d11922de3c81":{
      "scriptId":"u0"},
    "f401ff710a1447f3bd159b42b0d59e53":{
      "scriptId":"u1"},
    "74eea0a9fac3471eb6de8e2ffce73cd1":{
      "scriptId":"u2"},
    "65251419b3824deda5208bed6923bb14":{
      "scriptId":"u3"},
    "044eec3f6440446e9e66b5457b3961b6":{
      "scriptId":"u4"},
    "e72fe13b40a4430db798377b4dda2b82":{
      "scriptId":"u5"},
    "46b61e6a64df4ae9b8f65f7df6a32f4e":{
      "scriptId":"u6"},
    "512a3a1b56ae455fa85ff660fdc70e32":{
      "scriptId":"u7"},
    "4d605ee3b4ca4fdebb5362677bdd48d1":{
      "scriptId":"u8"},
    "25efaf53a25249c9b1b75d30445aa6ce":{
      "scriptId":"u9"},
    "f7f2d29b6aed4e499642a8b25ebcb214":{
      "scriptId":"u10"},
    "032b46c109c14a61afced8874ab8e2d4":{
      "scriptId":"u11"},
    "d194c14d4e624b7e84b8dacdd15b4ad5":{
      "scriptId":"u12"},
    "a176bfeb414043b183bc06f8abbc5a66":{
      "scriptId":"u13"},
    "17f1152afb1e49a68aa7b05a6ca7e5f2":{
      "scriptId":"u14"},
    "f4a7732919bc48bc88762758f9881bf3":{
      "scriptId":"u15"},
    "5e7a1d2102dd4685997f149580ad62a9":{
      "scriptId":"u16"},
    "902ab1b3dcda4914b267e661ce9bc604":{
      "scriptId":"u17"},
    "5f5030c2f7854475b9a5cc1248ec5cda":{
      "scriptId":"u18"},
    "6bf6357ed7ac499784e3627b6013cfe8":{
      "scriptId":"u19"},
    "c93ef6aea903440d83826235d1382b38":{
      "scriptId":"u20"},
    "d5ef75e8d13146c8a8217503f92a1838":{
      "scriptId":"u21"},
    "8027d2bf11214fbcb61375789a5dce3a":{
      "scriptId":"u22"},
    "e176223f4c714b20b6d79428a3cb3edf":{
      "scriptId":"u23"},
    "08bac5b10c954150a191cdd4e1d5e14b":{
      "scriptId":"u24"},
    "433a81e14cfd44abbdf26ad16edc3e2d":{
      "scriptId":"u25"},
    "d51b08eb78914cb6b2955077570db51f":{
      "scriptId":"u26"},
    "64e17d5d784244789670dac642dcaac1":{
      "scriptId":"u27"},
    "ac64da514a5a45d1ac241a494beeeb57":{
      "scriptId":"u28"},
    "7b321d6bffcf481d954762dad054039d":{
      "scriptId":"u29"},
    "1cce5af450f44befaebc89895fa8ec31":{
      "scriptId":"u30"},
    "63273ee7612e42049c85618f16b9ea73":{
      "scriptId":"u31"},
    "295d1a68244c42b7b7190660fa2a9c78":{
      "scriptId":"u32"},
    "c1b628f30f254c2cb12dd794114b4093":{
      "scriptId":"u33"},
    "9414c7bebc784c1bbb4ae3a04ff3333b":{
      "scriptId":"u34"},
    "4e1127265fe8473f8a44b945e97c2e03":{
      "scriptId":"u35"},
    "e5d26c6a6b1f4e1f916b4327e1758d90":{
      "scriptId":"u36"},
    "783939637bc74e4a840882d372d92824":{
      "scriptId":"u37"},
    "52304a1c65b8437ca5d45c54e9956499":{
      "scriptId":"u38"},
    "944dfccb0f9e4841a99a623c3366efa8":{
      "scriptId":"u39"},
    "f2c8a63fdc9749ec8547277e111aae5a":{
      "scriptId":"u40"},
    "b204d2ddbde0455fb1b625d1edd5d40d":{
      "scriptId":"u41"},
    "c98776da7b7641e7ac4e178179f328d2":{
      "scriptId":"u42"},
    "cee47f7beb684cf6b866428fd813089a":{
      "scriptId":"u43"},
    "be914053ac7149a58c5206a2668e2a9b":{
      "scriptId":"u44"},
    "edf10e537df242f3b935a2f8bbe81f25":{
      "scriptId":"u45"},
    "ecb90bda3bd24844960ebd4162719e34":{
      "scriptId":"u46"},
    "42454bbbd12d4fd086704a7ec18d1b77":{
      "scriptId":"u47"},
    "f6dd7a408eaa41b6b0bd606a5e6e4ce0":{
      "scriptId":"u48"},
    "35719baf23ab4a6f93bc9d2755498cdd":{
      "scriptId":"u49"},
    "7e0297fcc6ff462a995d336da8ed4311":{
      "scriptId":"u50"},
    "e15fd5e1127a493abdb66c6983e3488e":{
      "scriptId":"u51"},
    "a4346c8800d6472e801aec318da41709":{
      "scriptId":"u52"},
    "c7f0e57f48724336939bac6bde8e065e":{
      "scriptId":"u53"},
    "3831e118a76e4d338e920b5be824cc70":{
      "scriptId":"u54"},
    "74f09add1fc44cc19fea454a49ccb679":{
      "scriptId":"u55"},
    "36ade854e8f74ad590c0c3c41c5130ed":{
      "scriptId":"u56"},
    "2d3dad0407ca43da8dbeb52464cf6435":{
      "scriptId":"u57"},
    "beae6232a3be4f3ca6a06cd8587b4293":{
      "scriptId":"u58"},
    "8c16bad742ab4cbb847f1247b741f03b":{
      "scriptId":"u59"},
    "403fb83e982c42aab7e2723cbc0d09db":{
      "scriptId":"u60"},
    "f48a270c79204eb182666b78999f8b78":{
      "scriptId":"u61"},
    "6d880040cb4c4b60ad434b744076d57c":{
      "scriptId":"u62"},
    "2cd9fbf1bb37495dbc7f27aea4ee6859":{
      "scriptId":"u63"},
    "42ccc9cb0413489bb08ea513b9ca1973":{
      "scriptId":"u64"},
    "f8fb1992d3df4000b9c938643bdc5f62":{
      "scriptId":"u65"},
    "bb1355a4c8134eb7b18bb77e582fef98":{
      "scriptId":"u66"},
    "98373ac741194346bd1d5af9d11bad69":{
      "scriptId":"u67"},
    "557b0275b43e46898a8fb121ea76e82b":{
      "scriptId":"u68"},
    "bb9ae8e92f914d8396a9d0a8beb09234":{
      "scriptId":"u69"},
    "f7d553fbf0b544f7889561f8e4def9d5":{
      "scriptId":"u70"},
    "606ec71b4faa4983924cf28796b5ca02":{
      "scriptId":"u71"},
    "d82c196aac1d4e34830a059c8d92936d":{
      "scriptId":"u72"},
    "a6166958c40e46b2b2b62fbde06a72db":{
      "scriptId":"u73"},
    "33b6432cd22a4eb09178d31ba8f592af":{
      "scriptId":"u74"},
    "62fa254a8fc741a3ab17637afd1cbee1":{
      "scriptId":"u75"},
    "17ed49a17b444f06a96629cb93363037":{
      "scriptId":"u76"},
    "447b08b487eb46959cfc9cd8118de244":{
      "scriptId":"u77"},
    "355ec3be03e3433f960d55e13e63fca8":{
      "scriptId":"u78"},
    "36c57e11d5174976a29dfe68d35cd58b":{
      "scriptId":"u79"},
    "f8ea728ea35841f7b94e9da19e6cdcca":{
      "scriptId":"u80"},
    "9abb918fbb444159808ca99851484f2b":{
      "scriptId":"u81"},
    "416d08d47e3c4790ad3bd664f0e08d85":{
      "scriptId":"u82"},
    "cbb18aba65a14a1d9c0f0f1e89404908":{
      "scriptId":"u83"}}});