$axure.loadCurrentPage({
  "url":"个人中心-我的反馈.html",
  "generationDate":new Date(1402041964320.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c44dd30a306a4a7ab7c5214a03d7bf7a",
    "type":"Axure:Page",
    "name":"个人中心-我的反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ea4cac0d3304e3e972d92cc36e0ba5f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":260},
            "size":{
              "width":721,
              "height":211}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d1230aca5ea46ada57092fa3a97b863",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":212,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b66cd9041f5c43e99bc0f6a2a8ec1b6b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":212,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u1.png"}},
{
              "id":"f48d9ecd65a940d7a19321834e351ac5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":212,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77cac0708ba04f08b18002267c83a242",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":212,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"Case 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"Open 个人中心-我的反馈-单个反馈 in Current Window",
                          "target":{
                            "targetType":"page",
                            "url":"个人中心-我的反馈-单个反馈.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/个人中心-我的反馈/u7.png"}},
{
              "id":"28bc183e2cae4e9a894290a2ec749b4b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":76},
                "size":{
                  "width":212,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a302cb082b748bdadb0f235965ff15e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":212,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u13.png"}},
{
              "id":"4a979e8f2c09493f8225129793607fc2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":212,
                  "y":0},
                "size":{
                  "width":254,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c766b9a07514428ca216897e6368721b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":212,
                      "y":0},
                    "size":{
                      "width":254,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u3.png"}},
{
              "id":"e75991f4472e48b38d8a98af7c50de29",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":212,
                  "y":30},
                "size":{
                  "width":254,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d0a30c1d1f264a8cb6e7f77dedc0048b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":212,
                      "y":30},
                    "size":{
                      "width":254,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u9.png"}},
{
              "id":"af50986d7e7247d2848aefa58c6362c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":212,
                  "y":76},
                "size":{
                  "width":254,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a88de44edd90444285791f765db71cc4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":212,
                      "y":76},
                    "size":{
                      "width":254,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u15.png"}},
{
              "id":"73fc1db0207c4a439006641bd2e021ac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":466,
                  "y":0},
                "size":{
                  "width":255,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7cc103618ddc4ebb865c2e79de13e8e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":466,
                      "y":0},
                    "size":{
                      "width":255,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u5.png"}},
{
              "id":"7527549d608b48dea476541e8ea091fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":466,
                  "y":30},
                "size":{
                  "width":255,
                  "height":46}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bcd50028d41e45908913cee19c999005",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":466,
                      "y":30},
                    "size":{
                      "width":255,
                      "height":46}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u11.png"}},
{
              "id":"5f61e647124b473ea80248580dd79760",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":466,
                  "y":76},
                "size":{
                  "width":255,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"755ee091811e4a509aa84b9d022e6a43",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":466,
                      "y":76},
                    "size":{
                      "width":255,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u17.png"}},
{
              "id":"62b9a1dd016d4389b8326cb3931b9675",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":121},
                "size":{
                  "width":212,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90cf23758ea14cadbd6a49229111f316",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":121},
                    "size":{
                      "width":212,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u13.png"}},
{
              "id":"d30feaa1b2f44e4cae17ee532a4e77fc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":212,
                  "y":121},
                "size":{
                  "width":254,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a37e76912d514698811d1c1de70d2ca8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":212,
                      "y":121},
                    "size":{
                      "width":254,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u15.png"}},
{
              "id":"69871c1dcce743f1bad6c14390054f1b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":466,
                  "y":121},
                "size":{
                  "width":255,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"76c5ab692f3e44db99291424b6740b01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":466,
                      "y":121},
                    "size":{
                      "width":255,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u17.png"}},
{
              "id":"55af2517d9d0454d8baf69d51943b97b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":166},
                "size":{
                  "width":212,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"73293949a6814c76a96f21289f5e4e98",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":166},
                    "size":{
                      "width":212,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u25.png"}},
{
              "id":"448477370aa245eebdff55c778fd86ca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":212,
                  "y":166},
                "size":{
                  "width":254,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a2d1883ab024ce1be910f020d2265a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":212,
                      "y":166},
                    "size":{
                      "width":254,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u27.png"}},
{
              "id":"9f320e62261b4edfb029f439192b94b4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":466,
                  "y":166},
                "size":{
                  "width":255,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"01614b76319f41c985491332cebe550e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":466,
                      "y":166},
                    "size":{
                      "width":255,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-我的反馈/u29.png"}}]},
{
          "id":"ee3b18c48c7440fb8d3cb41a6e289d3f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":530},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a8d4a6cdc1c7400f9ac48a2d6cea1447",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":530},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7e31357e31a8441281c1ca056b375374",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":484,
              "y":534},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45d2f299ac0d4d15bffc5e1a0f72d521",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":484,
                  "y":534},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea536e54f4d74f8a8d7a2eb1334f0f5a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":1000,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0c72b5f2ed841e5aa6e12d7365e2e30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":1000,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"8e1cce65195042268829b560546eabc1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"5636949169224b568e7ce9ead90e326c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f0462d524be1499da5fb1a6cadcb5092",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d2ed00b7133b4d60995daa6738a59ffe",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f55fe0569bed4702816506f3c277dc1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":7},
            "size":{
              "width":90,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83a8b0854a3d426eb944b7190ab47daf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":7},
                "size":{
                  "width":90,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06c63bd439924a8a9e57a0c07a2a4f2a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":0},
            "size":{
              "width":100,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"130e809b18464d3d898fb2ef90b64462",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3e92100f17af4301a9785f51d4505733",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":200},
            "size":{
              "width":169,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beee3e31a4c5481e9ddae206947a3df5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":169,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-个人信息/u48.png"}},
{
          "id":"a83d5b8f47e84647b6d5d6909d3e7ea3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":-10,
              "y":632},
            "size":{
              "width":1000,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f110a1c651dd4a389892e98fcc7dfaa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":-10,
                  "y":632},
                "size":{
                  "width":1000,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u46.png"}},
{
          "id":"bd984e13291844069eaaae0ee0af8509",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心-个人信息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8477ed6d46d54669baae235031a2ceff",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":430},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in New Window/Tab",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"8d6f4d6338794d54a342beb227eb56e6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":480},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in New Window/Tab",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"28aeb3cf53134cc2a092e87777907922",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":530},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心-订单管理 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-订单管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"11d06c86328e420eb3673a57fd38716a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":580},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "5ea4cac0d3304e3e972d92cc36e0ba5f":{
      "scriptId":"u0"},
    "0d1230aca5ea46ada57092fa3a97b863":{
      "scriptId":"u1"},
    "b66cd9041f5c43e99bc0f6a2a8ec1b6b":{
      "scriptId":"u2"},
    "4a979e8f2c09493f8225129793607fc2":{
      "scriptId":"u3"},
    "c766b9a07514428ca216897e6368721b":{
      "scriptId":"u4"},
    "73fc1db0207c4a439006641bd2e021ac":{
      "scriptId":"u5"},
    "7cc103618ddc4ebb865c2e79de13e8e2":{
      "scriptId":"u6"},
    "f48d9ecd65a940d7a19321834e351ac5":{
      "scriptId":"u7"},
    "77cac0708ba04f08b18002267c83a242":{
      "scriptId":"u8"},
    "e75991f4472e48b38d8a98af7c50de29":{
      "scriptId":"u9"},
    "d0a30c1d1f264a8cb6e7f77dedc0048b":{
      "scriptId":"u10"},
    "7527549d608b48dea476541e8ea091fe":{
      "scriptId":"u11"},
    "bcd50028d41e45908913cee19c999005":{
      "scriptId":"u12"},
    "28bc183e2cae4e9a894290a2ec749b4b":{
      "scriptId":"u13"},
    "1a302cb082b748bdadb0f235965ff15e":{
      "scriptId":"u14"},
    "af50986d7e7247d2848aefa58c6362c3":{
      "scriptId":"u15"},
    "a88de44edd90444285791f765db71cc4":{
      "scriptId":"u16"},
    "5f61e647124b473ea80248580dd79760":{
      "scriptId":"u17"},
    "755ee091811e4a509aa84b9d022e6a43":{
      "scriptId":"u18"},
    "62b9a1dd016d4389b8326cb3931b9675":{
      "scriptId":"u19"},
    "90cf23758ea14cadbd6a49229111f316":{
      "scriptId":"u20"},
    "d30feaa1b2f44e4cae17ee532a4e77fc":{
      "scriptId":"u21"},
    "a37e76912d514698811d1c1de70d2ca8":{
      "scriptId":"u22"},
    "69871c1dcce743f1bad6c14390054f1b":{
      "scriptId":"u23"},
    "76c5ab692f3e44db99291424b6740b01":{
      "scriptId":"u24"},
    "55af2517d9d0454d8baf69d51943b97b":{
      "scriptId":"u25"},
    "73293949a6814c76a96f21289f5e4e98":{
      "scriptId":"u26"},
    "448477370aa245eebdff55c778fd86ca":{
      "scriptId":"u27"},
    "5a2d1883ab024ce1be910f020d2265a2":{
      "scriptId":"u28"},
    "9f320e62261b4edfb029f439192b94b4":{
      "scriptId":"u29"},
    "01614b76319f41c985491332cebe550e":{
      "scriptId":"u30"},
    "ee3b18c48c7440fb8d3cb41a6e289d3f":{
      "scriptId":"u31"},
    "a8d4a6cdc1c7400f9ac48a2d6cea1447":{
      "scriptId":"u32"},
    "7e31357e31a8441281c1ca056b375374":{
      "scriptId":"u33"},
    "45d2f299ac0d4d15bffc5e1a0f72d521":{
      "scriptId":"u34"},
    "ea536e54f4d74f8a8d7a2eb1334f0f5a":{
      "scriptId":"u35"},
    "e0c72b5f2ed841e5aa6e12d7365e2e30":{
      "scriptId":"u36"},
    "8e1cce65195042268829b560546eabc1":{
      "scriptId":"u37"},
    "5636949169224b568e7ce9ead90e326c":{
      "scriptId":"u38"},
    "f0462d524be1499da5fb1a6cadcb5092":{
      "scriptId":"u39"},
    "d2ed00b7133b4d60995daa6738a59ffe":{
      "scriptId":"u40"},
    "f55fe0569bed4702816506f3c277dc1c":{
      "scriptId":"u41"},
    "83a8b0854a3d426eb944b7190ab47daf":{
      "scriptId":"u42"},
    "06c63bd439924a8a9e57a0c07a2a4f2a":{
      "scriptId":"u43"},
    "130e809b18464d3d898fb2ef90b64462":{
      "scriptId":"u44"},
    "3e92100f17af4301a9785f51d4505733":{
      "scriptId":"u45"},
    "beee3e31a4c5481e9ddae206947a3df5":{
      "scriptId":"u46"},
    "a83d5b8f47e84647b6d5d6909d3e7ea3":{
      "scriptId":"u47"},
    "f110a1c651dd4a389892e98fcc7dfaa7":{
      "scriptId":"u48"},
    "bd984e13291844069eaaae0ee0af8509":{
      "scriptId":"u49"},
    "8477ed6d46d54669baae235031a2ceff":{
      "scriptId":"u50"},
    "8d6f4d6338794d54a342beb227eb56e6":{
      "scriptId":"u51"},
    "28aeb3cf53134cc2a092e87777907922":{
      "scriptId":"u52"},
    "11d06c86328e420eb3673a57fd38716a":{
      "scriptId":"u53"}}});