$axure.loadCurrentPage({
  "url":"购物车.html",
  "generationDate":new Date(1402041962384.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3fb4dc7f1b464897a148e247affe2644",
    "type":"Axure:Page",
    "name":"购物车",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"78591696b0c64cdabadac20f554a31f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":195},
            "size":{
              "width":90,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4814fce5432847e5a464bc2b588dfef1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":195},
                "size":{
                  "width":90,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u0.jpg"}},
{
          "id":"d863cea676c541959a787afdcfed36f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":97,
              "y":216},
            "size":{
              "width":100,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b213516b8cfc4eea804b5f0bb1d76212",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":97,
                  "y":216},
                "size":{
                  "width":100,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfdae55e25a04f4e989c773c99effffa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":286},
            "size":{
              "width":982,
              "height":414}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa137a3056ad4e47825357e85b5ab5b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":286},
                "size":{
                  "width":982,
                  "height":414}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u4.png"}},
{
          "id":"ec62dbb4944a46c1b99f51014b62664c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":345},
            "size":{
              "width":957,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购物车/u6_line.png"}},
{
          "id":"523d92a574414ccb9a8d5752c401cf8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":694,
              "y":320},
            "size":{
              "width":126,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d5f58c89a4c4b49a85ee156a988cf34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":694,
                  "y":320},
                "size":{
                  "width":126,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf01be5967b8494e8b89ffaa53f541f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":320},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa0e491e6095487596860813a6065270",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":320},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ed8a1af6a324784ab791cde582c2115",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":29,
              "y":299},
            "size":{
              "width":131,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f5aac2c78c94b8e9bc225fe2495456f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":29,
                  "y":299},
                "size":{
                  "width":131,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49da85df91a54fc58320ee5aa567f82b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":153,
              "y":304},
            "size":{
              "width":12,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c2ca976d2f64f42b2bc7d2c0dd24020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":153,
                  "y":304},
                "size":{
                  "width":12,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbe0c202013e4080a7a2fdbccf06cf3c",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":369},
            "size":{
              "width":912,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc41304427f145f29a4d2010c84d1810",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":444,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0739b9f9aa8d42379bd497c5e6a6a20b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":444,
                      "height":57},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u16.png"}},
{
              "id":"1927ab16df7648769e6f7500dca936fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":444,
                  "y":0},
                "size":{
                  "width":136,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f4fabab46854406cb1ece33bae5acb5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":444,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":57},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u18.png"}},
{
              "id":"a4136c325eb640cd900ad08dee8a82c9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":580,
                  "y":0},
                "size":{
                  "width":111,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dcf345ae206e41ffb9f004e6008dbbb3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":580,
                      "y":0},
                    "size":{
                      "width":111,
                      "height":57},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u20.png"}},
{
              "id":"fb5eac6d280943b49d73a0bd3ec30b97",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":691,
                  "y":0},
                "size":{
                  "width":117,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74e9b93b43854ddd9d3d2ff077a3307d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":691,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":57},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u22.png"}},
{
              "id":"b34f5dfe91594ebc930c511e3a549523",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":808,
                  "y":0},
                "size":{
                  "width":104,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2123d07c6ad748c9804ac3dd48ce2bb6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":808,
                      "y":0},
                    "size":{
                      "width":104,
                      "height":57},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u24.png"}}]},
{
          "id":"1e1061ea8690458699884d98b680a94a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":471},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cac2dfb86da4f44b472879796cef2d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":471},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"280ba75151064e74a778c8412e4d32ca",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":387},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4af688734df7406f96e0e0ea01f50b36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":387},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e62bc7f11fd74c328881a77d98cf95df",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":436},
            "size":{
              "width":919,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1734505bdb7142bf9292b9597f1bf954",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":53,
                  "y":0},
                "size":{
                  "width":401,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"60150c109aaa4a7eb2350be85a7eab21",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":53,
                      "y":0},
                    "size":{
                      "width":401,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u33.png"}},
{
              "id":"41ccb50c0d0b44f5a716f831150e1e70",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":696,
                  "y":0},
                "size":{
                  "width":125,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"96b7c219dac041c1b0900c05dd5bdc83",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":696,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u39.png"}},
{
              "id":"0e4a39fa4b9f4029ab6fcc784f3e37df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":821,
                  "y":0},
                "size":{
                  "width":98,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49592635644e427e87fb38d8d6ba65d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":821,
                      "y":0},
                    "size":{
                      "width":98,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u41.png"}},
{
              "id":"cbed416be2e344f3bce94f47dc20bc16",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":586,
                  "y":0},
                "size":{
                  "width":110,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"570326d97d0b429db1b026710c8538a4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":586,
                      "y":0},
                    "size":{
                      "width":110,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u37.png"}},
{
              "id":"ddff8a0abe3d4b31bb692136e408ad09",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":454,
                  "y":0},
                "size":{
                  "width":132,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24bcd29bf0764c69afa290d9fe61a5fe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":454,
                      "y":0},
                    "size":{
                      "width":132,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u35.png"}},
{
              "id":"62255459af7d48ef889eee552b705ee9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":53,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7fc6bb8c2235426395ba97e22974d1f8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":53,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u31.png"}},
{
              "id":"0a6a88e08cde4e3b86b1fd785a728c44",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":77},
                "size":{
                  "width":53,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"80411b87a2c44c1b94f359a8b86b02b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":77},
                    "size":{
                      "width":53,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u43.png"}},
{
              "id":"912101ba92ab49eebb155b8b977aef6d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":53,
                  "y":77},
                "size":{
                  "width":401,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41b586e4850542ba89b3cb5425b9ffa8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":53,
                      "y":77},
                    "size":{
                      "width":401,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u45.png"}},
{
              "id":"62430568205646b88421b331a7858e9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":454,
                  "y":77},
                "size":{
                  "width":132,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"73403bd500cf4e35bf2b57324555e58d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":454,
                      "y":77},
                    "size":{
                      "width":132,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u47.png"}},
{
              "id":"3992109c9bf2402eb9514f449d6354ae",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":586,
                  "y":77},
                "size":{
                  "width":110,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a09370bfdab04d75aec23a3ea8056112",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":586,
                      "y":77},
                    "size":{
                      "width":110,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u49.png"}},
{
              "id":"5f625687a9254297a58a5a5be7b12a6e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":696,
                  "y":77},
                "size":{
                  "width":125,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3db61090ef384df1a477726ea9834fab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":696,
                      "y":77},
                    "size":{
                      "width":125,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u51.png"}},
{
              "id":"eb102acb02e54023afa58211c42a5c39",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":821,
                  "y":77},
                "size":{
                  "width":98,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"03798188cf16447f959baac9bd610947",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":821,
                      "y":77},
                    "size":{
                      "width":98,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/购物车/u53.png"}}]},
{
          "id":"5e6059925f40458880fd0a6d32d0c0da",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":416},
            "size":{
              "width":947,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购物车/u55_line.png"}},
{
          "id":"a3e7005c39b442c8aaeeaca88a7bc137",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":879.5,
              "y":444},
            "size":{
              "width":71,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"191d30883b7049debd1e7541b01d07f6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":479},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"16fdce590bdf452ea589981e0866ddc3",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":467},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c071beeaf3f44e429c5c2657dad38230",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":467},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5c0103cb88c04f30ab67bb81f00b685d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":548},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a2e33a0db4d4a4c96bae6051d109362",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":548},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"065cae50477b4d03aa5120a72e94da3e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":525},
            "size":{
              "width":71,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"874bbed2bac0434ca3b1516a3d4a4199",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":881,
              "y":559},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c2bcf04790324cecb6498065196535e5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":667,
              "y":216},
            "size":{
              "width":233,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"f669f991b36c40ebb37ee559b701cd93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":910,
              "y":216},
            "size":{
              "width":92,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a5eee060a0440c1b71b82acf18df7ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":910,
                  "y":216},
                "size":{
                  "width":92,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u65.png"}},
{
          "id":"7ef5edf720ac421a96ac7dad8a01bdea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":1000,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73827ccf8d7c48748404ecc0c3f60dde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":1000,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"d14c1ed1aa844bba8978cabbd0a58e9b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"ee08f8d957474bcfbb00b7658d691e2a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"553545f897e344ed85470b280d044ba8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e8b7bd2133d4414dbb328f6de9f2d429",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"cfd1be8e068d445789e5b41b1f0ff306",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":655},
            "size":{
              "width":71,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e6ccae9a1e9f497da386da6ba0155135",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":655},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a1a20199b54f494b90830e634900a410",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":7},
            "size":{
              "width":90,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0f2de21ce2441cea03a14e4e2eb6b90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":7},
                "size":{
                  "width":90,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5d493676bef447dbd9d3d5726d66968",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":0},
            "size":{
              "width":100,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"e24273d701a745f8b718455445a9b35f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":0,
              "y":710},
            "size":{
              "width":1000,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72c48e3619a847cf9f54b8f37124fe87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":0,
                  "y":710},
                "size":{
                  "width":1000,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u46.png"}},
{
          "id":"2cb4ebd91a7b498bbba295f9c7a537fd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "78591696b0c64cdabadac20f554a31f0":{
      "scriptId":"u0"},
    "4814fce5432847e5a464bc2b588dfef1":{
      "scriptId":"u1"},
    "d863cea676c541959a787afdcfed36f0":{
      "scriptId":"u2"},
    "b213516b8cfc4eea804b5f0bb1d76212":{
      "scriptId":"u3"},
    "bfdae55e25a04f4e989c773c99effffa":{
      "scriptId":"u4"},
    "aa137a3056ad4e47825357e85b5ab5b8":{
      "scriptId":"u5"},
    "ec62dbb4944a46c1b99f51014b62664c":{
      "scriptId":"u6"},
    "523d92a574414ccb9a8d5752c401cf8d":{
      "scriptId":"u7"},
    "8d5f58c89a4c4b49a85ee156a988cf34":{
      "scriptId":"u8"},
    "bf01be5967b8494e8b89ffaa53f541f6":{
      "scriptId":"u9"},
    "fa0e491e6095487596860813a6065270":{
      "scriptId":"u10"},
    "8ed8a1af6a324784ab791cde582c2115":{
      "scriptId":"u11"},
    "4f5aac2c78c94b8e9bc225fe2495456f":{
      "scriptId":"u12"},
    "49da85df91a54fc58320ee5aa567f82b":{
      "scriptId":"u13"},
    "5c2ca976d2f64f42b2bc7d2c0dd24020":{
      "scriptId":"u14"},
    "dbe0c202013e4080a7a2fdbccf06cf3c":{
      "scriptId":"u15"},
    "dc41304427f145f29a4d2010c84d1810":{
      "scriptId":"u16"},
    "0739b9f9aa8d42379bd497c5e6a6a20b":{
      "scriptId":"u17"},
    "1927ab16df7648769e6f7500dca936fe":{
      "scriptId":"u18"},
    "f4fabab46854406cb1ece33bae5acb5b":{
      "scriptId":"u19"},
    "a4136c325eb640cd900ad08dee8a82c9":{
      "scriptId":"u20"},
    "dcf345ae206e41ffb9f004e6008dbbb3":{
      "scriptId":"u21"},
    "fb5eac6d280943b49d73a0bd3ec30b97":{
      "scriptId":"u22"},
    "74e9b93b43854ddd9d3d2ff077a3307d":{
      "scriptId":"u23"},
    "b34f5dfe91594ebc930c511e3a549523":{
      "scriptId":"u24"},
    "2123d07c6ad748c9804ac3dd48ce2bb6":{
      "scriptId":"u25"},
    "1e1061ea8690458699884d98b680a94a":{
      "scriptId":"u26"},
    "3cac2dfb86da4f44b472879796cef2d3":{
      "scriptId":"u27"},
    "280ba75151064e74a778c8412e4d32ca":{
      "scriptId":"u28"},
    "4af688734df7406f96e0e0ea01f50b36":{
      "scriptId":"u29"},
    "e62bc7f11fd74c328881a77d98cf95df":{
      "scriptId":"u30"},
    "62255459af7d48ef889eee552b705ee9":{
      "scriptId":"u31"},
    "7fc6bb8c2235426395ba97e22974d1f8":{
      "scriptId":"u32"},
    "1734505bdb7142bf9292b9597f1bf954":{
      "scriptId":"u33"},
    "60150c109aaa4a7eb2350be85a7eab21":{
      "scriptId":"u34"},
    "ddff8a0abe3d4b31bb692136e408ad09":{
      "scriptId":"u35"},
    "24bcd29bf0764c69afa290d9fe61a5fe":{
      "scriptId":"u36"},
    "cbed416be2e344f3bce94f47dc20bc16":{
      "scriptId":"u37"},
    "570326d97d0b429db1b026710c8538a4":{
      "scriptId":"u38"},
    "41ccb50c0d0b44f5a716f831150e1e70":{
      "scriptId":"u39"},
    "96b7c219dac041c1b0900c05dd5bdc83":{
      "scriptId":"u40"},
    "0e4a39fa4b9f4029ab6fcc784f3e37df":{
      "scriptId":"u41"},
    "49592635644e427e87fb38d8d6ba65d4":{
      "scriptId":"u42"},
    "0a6a88e08cde4e3b86b1fd785a728c44":{
      "scriptId":"u43"},
    "80411b87a2c44c1b94f359a8b86b02b9":{
      "scriptId":"u44"},
    "912101ba92ab49eebb155b8b977aef6d":{
      "scriptId":"u45"},
    "41b586e4850542ba89b3cb5425b9ffa8":{
      "scriptId":"u46"},
    "62430568205646b88421b331a7858e9b":{
      "scriptId":"u47"},
    "73403bd500cf4e35bf2b57324555e58d":{
      "scriptId":"u48"},
    "3992109c9bf2402eb9514f449d6354ae":{
      "scriptId":"u49"},
    "a09370bfdab04d75aec23a3ea8056112":{
      "scriptId":"u50"},
    "5f625687a9254297a58a5a5be7b12a6e":{
      "scriptId":"u51"},
    "3db61090ef384df1a477726ea9834fab":{
      "scriptId":"u52"},
    "eb102acb02e54023afa58211c42a5c39":{
      "scriptId":"u53"},
    "03798188cf16447f959baac9bd610947":{
      "scriptId":"u54"},
    "5e6059925f40458880fd0a6d32d0c0da":{
      "scriptId":"u55"},
    "a3e7005c39b442c8aaeeaca88a7bc137":{
      "scriptId":"u56"},
    "191d30883b7049debd1e7541b01d07f6":{
      "scriptId":"u57"},
    "16fdce590bdf452ea589981e0866ddc3":{
      "scriptId":"u58"},
    "c071beeaf3f44e429c5c2657dad38230":{
      "scriptId":"u59"},
    "5c0103cb88c04f30ab67bb81f00b685d":{
      "scriptId":"u60"},
    "1a2e33a0db4d4a4c96bae6051d109362":{
      "scriptId":"u61"},
    "065cae50477b4d03aa5120a72e94da3e":{
      "scriptId":"u62"},
    "874bbed2bac0434ca3b1516a3d4a4199":{
      "scriptId":"u63"},
    "c2bcf04790324cecb6498065196535e5":{
      "scriptId":"u64"},
    "f669f991b36c40ebb37ee559b701cd93":{
      "scriptId":"u65"},
    "8a5eee060a0440c1b71b82acf18df7ac":{
      "scriptId":"u66"},
    "7ef5edf720ac421a96ac7dad8a01bdea":{
      "scriptId":"u67"},
    "73827ccf8d7c48748404ecc0c3f60dde":{
      "scriptId":"u68"},
    "d14c1ed1aa844bba8978cabbd0a58e9b":{
      "scriptId":"u69"},
    "ee08f8d957474bcfbb00b7658d691e2a":{
      "scriptId":"u70"},
    "553545f897e344ed85470b280d044ba8":{
      "scriptId":"u71"},
    "e8b7bd2133d4414dbb328f6de9f2d429":{
      "scriptId":"u72"},
    "cfd1be8e068d445789e5b41b1f0ff306":{
      "scriptId":"u73"},
    "e6ccae9a1e9f497da386da6ba0155135":{
      "scriptId":"u74"},
    "a1a20199b54f494b90830e634900a410":{
      "scriptId":"u75"},
    "a0f2de21ce2441cea03a14e4e2eb6b90":{
      "scriptId":"u76"},
    "c5d493676bef447dbd9d3d5726d66968":{
      "scriptId":"u77"},
    "e24273d701a745f8b718455445a9b35f":{
      "scriptId":"u78"},
    "72c48e3619a847cf9f54b8f37124fe87":{
      "scriptId":"u79"},
    "2cb4ebd91a7b498bbba295f9c7a537fd":{
      "scriptId":"u80"}}});