$axure.loadCurrentPage({
  "url":"个人中心-个人信息.html",
  "generationDate":new Date(1402041963004.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"653f9c8345dd4a059cb6f62955177627",
    "type":"Axure:Page",
    "name":"个人中心-个人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fbc55d65bfde4494afc56c3f57d3bffd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":210},
            "size":{
              "width":701,
              "height":372}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8208a299c117453a9512a17d2994fdbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":179,
                  "y":210},
                "size":{
                  "width":701,
                  "height":372}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-个人信息/u0.png"}},
{
          "id":"62969f24ec8c48788c4596da69b79b27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":210,
              "y":244},
            "size":{
              "width":65,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14ec6181acaf42b8a9043bb8c729d40b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":210,
                  "y":244},
                "size":{
                  "width":65,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29cf26d6b0f04c358d18311eb7c35168",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":216,
              "y":299},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d7cfea987fb40b4ba5b724b74b0668c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":216,
                  "y":299},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb973bfcc5a14470a07b5e5d949f9c7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":215,
              "y":332},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3156283d02bf434a8f3c3db953d6ec17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":215,
                  "y":332},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e075d27dd83b4d4eb41c9c8ba9a54b85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":218,
              "y":393},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98340cb88bcb4b21851e7d1a87a1ad89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":218,
                  "y":393},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8518237409fb43b5aefc80d099232471",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":214,
              "y":428},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76011bd092ce4ef0a6ec176b70abc5ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":214,
                  "y":428},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b399d86b69244e14964b4886dbbbf553",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":290},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b9c619a8c94e4b4c831fdfd85c50adcd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":325},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1a361f1b271e4f7a9075c00717b32b5c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":393},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef0c5e4efd542a4988563a0f5215191",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":393},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a278378bb5bd4cf594c9cdcc877e14ba",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":393},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"259846f754c948d4a82f1843f70d35e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":393},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6fd2176c97bf43a088581a5a0a98b028",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":283.5,
              "y":419},
            "size":{
              "width":62,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5f6959264b34412abde199e7f037ad3a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":360.5,
              "y":419},
            "size":{
              "width":40,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b3c4c064408848ab9eafd1ea2531ce52",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":411.5,
              "y":419},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"904e6c53786b437f99138c5882fb027b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":358},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"aae983e703b3411db40b5bd530c8692e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":364},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46e46b8fd3214273b7d163f230e496f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":364},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a27f709261194dfab289d1dc59ae9a1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":504},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1dd1e5cdc8f450cbb1d1d78f474b566",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":504},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba1c03b70ee54a7eb5d11145965ef5c9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":501},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8b979471b1224445b26559996484aecb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":744,
              "y":248},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51b36c1836e240f7ac8cecc6d89b3d4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":744,
                  "y":248},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e66857f4ac0485b8fd3a6ff087fa386",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":781,
              "y":248},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"453f608dd5bb4beda47502759c67f5c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":781,
                  "y":248},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"131b428393c94e958573c4dbdbcc0378",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":474,
              "y":423},
            "size":{
              "width":120,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c428ff578d4242d2ab4a2ef9ae8c7c14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":474,
                  "y":423},
                "size":{
                  "width":120,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab00d69f4df44d34b578089a8ccaa63a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":506,
              "y":305},
            "size":{
              "width":256,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"188f9b97add64d0fb75e42f72637cec5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":506,
                  "y":305},
                "size":{
                  "width":256,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5f09700935f42b4850f36808452f5b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":248},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6a469353a724827850a4fe8dde98264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":248},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d63f88a228074395ab051c3de176a88b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":269},
            "size":{
              "width":645,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人中心-个人信息/u37_line.png"}},
{
          "id":"28dcd598ba0141d883b70056152ecda2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":1000,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dedfc0211f7d4018b230fae8f7ee24bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":1000,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"ef014ce5bee44138bc945105b3127a5c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"7a9fb596f8d245d6882de01f3c95b90a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d2d9587382a84d2497dc4af757c33a3b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d28915481df843ffaa7c11364f667a96",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"fef083a0805d457194dd56fb204ef2ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":7},
            "size":{
              "width":90,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f06d4bc9cb654844995465d44ce8d5e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":7},
                "size":{
                  "width":90,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21ff8b7b85134982953db615ac6ffb5d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":0},
            "size":{
              "width":100,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"da6e2dea8ced4b20ae50bb5644cd0aa8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0b8f15a381944f86ba143b2ee50767ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":200},
            "size":{
              "width":169,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b329650a27a47dc9fd2237a087bd16c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":169,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-个人信息/u48.png"}},
{
          "id":"08720018295149809b226667ca2576b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":-10,
              "y":632},
            "size":{
              "width":1000,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9fff5cb3b1441b7b9a8a3eb5ae42639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":-10,
                  "y":632},
                "size":{
                  "width":1000,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u46.png"}},
{
          "id":"439b6b8ee45b4a87b88509ff591a6636",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心-个人信息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2152ba6887cc4f4eb22eb030a251643f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":410},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in New Window/Tab",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"364f217b13e545199ef90caf652b7870",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":440},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in New Window/Tab",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"85f8847e478949b6b2e0f6a9bf2f9367",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":470},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心-订单管理 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-订单管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4a8e7733746f435e91c3215b9ca032e9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":500},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心-我的反馈 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-我的反馈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7940217cb6e447b39bac6109af2ab313",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":781,
              "y":210},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0e5edcced47e4af1a6298ba639422ba5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":464},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41d271df2b554f9982287767b46eaae7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":464},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd50616f167642adb1be66e450471542",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":530},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"faa92f1c4c0346a8868fb2f24d01e1c4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":560},
            "size":{
              "width":169,
              "height":30}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "fbc55d65bfde4494afc56c3f57d3bffd":{
      "scriptId":"u0"},
    "8208a299c117453a9512a17d2994fdbc":{
      "scriptId":"u1"},
    "62969f24ec8c48788c4596da69b79b27":{
      "scriptId":"u2"},
    "14ec6181acaf42b8a9043bb8c729d40b":{
      "scriptId":"u3"},
    "29cf26d6b0f04c358d18311eb7c35168":{
      "scriptId":"u4"},
    "9d7cfea987fb40b4ba5b724b74b0668c":{
      "scriptId":"u5"},
    "fb973bfcc5a14470a07b5e5d949f9c7f":{
      "scriptId":"u6"},
    "3156283d02bf434a8f3c3db953d6ec17":{
      "scriptId":"u7"},
    "e075d27dd83b4d4eb41c9c8ba9a54b85":{
      "scriptId":"u8"},
    "98340cb88bcb4b21851e7d1a87a1ad89":{
      "scriptId":"u9"},
    "8518237409fb43b5aefc80d099232471":{
      "scriptId":"u10"},
    "76011bd092ce4ef0a6ec176b70abc5ad":{
      "scriptId":"u11"},
    "b399d86b69244e14964b4886dbbbf553":{
      "scriptId":"u12"},
    "b9c619a8c94e4b4c831fdfd85c50adcd":{
      "scriptId":"u13"},
    "1a361f1b271e4f7a9075c00717b32b5c":{
      "scriptId":"u14"},
    "8ef0c5e4efd542a4988563a0f5215191":{
      "scriptId":"u15"},
    "a278378bb5bd4cf594c9cdcc877e14ba":{
      "scriptId":"u16"},
    "259846f754c948d4a82f1843f70d35e0":{
      "scriptId":"u17"},
    "6fd2176c97bf43a088581a5a0a98b028":{
      "scriptId":"u18"},
    "5f6959264b34412abde199e7f037ad3a":{
      "scriptId":"u19"},
    "b3c4c064408848ab9eafd1ea2531ce52":{
      "scriptId":"u20"},
    "904e6c53786b437f99138c5882fb027b":{
      "scriptId":"u21"},
    "aae983e703b3411db40b5bd530c8692e":{
      "scriptId":"u22"},
    "46e46b8fd3214273b7d163f230e496f7":{
      "scriptId":"u23"},
    "a27f709261194dfab289d1dc59ae9a1c":{
      "scriptId":"u24"},
    "d1dd1e5cdc8f450cbb1d1d78f474b566":{
      "scriptId":"u25"},
    "ba1c03b70ee54a7eb5d11145965ef5c9":{
      "scriptId":"u26"},
    "8b979471b1224445b26559996484aecb":{
      "scriptId":"u27"},
    "51b36c1836e240f7ac8cecc6d89b3d4a":{
      "scriptId":"u28"},
    "2e66857f4ac0485b8fd3a6ff087fa386":{
      "scriptId":"u29"},
    "453f608dd5bb4beda47502759c67f5c0":{
      "scriptId":"u30"},
    "131b428393c94e958573c4dbdbcc0378":{
      "scriptId":"u31"},
    "c428ff578d4242d2ab4a2ef9ae8c7c14":{
      "scriptId":"u32"},
    "ab00d69f4df44d34b578089a8ccaa63a":{
      "scriptId":"u33"},
    "188f9b97add64d0fb75e42f72637cec5":{
      "scriptId":"u34"},
    "d5f09700935f42b4850f36808452f5b7":{
      "scriptId":"u35"},
    "b6a469353a724827850a4fe8dde98264":{
      "scriptId":"u36"},
    "d63f88a228074395ab051c3de176a88b":{
      "scriptId":"u37"},
    "28dcd598ba0141d883b70056152ecda2":{
      "scriptId":"u38"},
    "dedfc0211f7d4018b230fae8f7ee24bb":{
      "scriptId":"u39"},
    "ef014ce5bee44138bc945105b3127a5c":{
      "scriptId":"u40"},
    "7a9fb596f8d245d6882de01f3c95b90a":{
      "scriptId":"u41"},
    "d2d9587382a84d2497dc4af757c33a3b":{
      "scriptId":"u42"},
    "d28915481df843ffaa7c11364f667a96":{
      "scriptId":"u43"},
    "fef083a0805d457194dd56fb204ef2ec":{
      "scriptId":"u44"},
    "f06d4bc9cb654844995465d44ce8d5e7":{
      "scriptId":"u45"},
    "21ff8b7b85134982953db615ac6ffb5d":{
      "scriptId":"u46"},
    "da6e2dea8ced4b20ae50bb5644cd0aa8":{
      "scriptId":"u47"},
    "0b8f15a381944f86ba143b2ee50767ca":{
      "scriptId":"u48"},
    "0b329650a27a47dc9fd2237a087bd16c":{
      "scriptId":"u49"},
    "08720018295149809b226667ca2576b2":{
      "scriptId":"u50"},
    "d9fff5cb3b1441b7b9a8a3eb5ae42639":{
      "scriptId":"u51"},
    "439b6b8ee45b4a87b88509ff591a6636":{
      "scriptId":"u52"},
    "2152ba6887cc4f4eb22eb030a251643f":{
      "scriptId":"u53"},
    "364f217b13e545199ef90caf652b7870":{
      "scriptId":"u54"},
    "85f8847e478949b6b2e0f6a9bf2f9367":{
      "scriptId":"u55"},
    "4a8e7733746f435e91c3215b9ca032e9":{
      "scriptId":"u56"},
    "7940217cb6e447b39bac6109af2ab313":{
      "scriptId":"u57"},
    "0e5edcced47e4af1a6298ba639422ba5":{
      "scriptId":"u58"},
    "41d271df2b554f9982287767b46eaae7":{
      "scriptId":"u59"},
    "bd50616f167642adb1be66e450471542":{
      "scriptId":"u60"},
    "faa92f1c4c0346a8868fb2f24d01e1c4":{
      "scriptId":"u61"}}});