$axure.loadCurrentPage({
  "url":"收藏夹.html",
  "generationDate":new Date(1402041962848.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7222716623cb41a88c05487110ed7026",
    "type":"Axure:Page",
    "name":"收藏夹",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fbe2887575c94f028e80f6798b34fa4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":1,
              "y":240},
            "size":{
              "width":1010,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5850559473c04990bf881e8b65c7d17b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":1,
                  "y":240},
                "size":{
                  "width":1010,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u0.png"}},
{
          "id":"d8412eb149a643a28ce9cf16c7532b17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":463},
            "size":{
              "width":230,
              "height":327}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b57589ab7514f90be71a543e9dac5f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":463},
                "size":{
                  "width":230,
                  "height":327}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u2.png"}},
{
          "id":"03ebd25423e246d19407a10d91069a1f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":260},
            "size":{
              "width":97,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e9b22bd690c4559980f8c020e764577",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":260},
                "size":{
                  "width":97,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u0.jpg"}},
{
          "id":"55f8c3353312417fb035a19bebec357d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'ParkAvenue BT Regular', 'ParkAvenue BT'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":114,
              "y":289},
            "size":{
              "width":123,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65779c984f9e447cbd8008cd69e89c9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'ParkAvenue BT Regular', 'ParkAvenue BT'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":114,
                  "y":289},
                "size":{
                  "width":123,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90a94a5adcbc45beb21b9b4da6b4a2c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":57,
              "y":477},
            "size":{
              "width":190,
              "height":220},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6c1ee3fa0ae405099170ab97ba68ef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":57,
                  "y":477},
                "size":{
                  "width":190,
                  "height":220},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u8.png"}},
{
          "id":"8cd12f92aed941e3aa4bafbbc07e7def",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":477},
            "size":{
              "width":157,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31fff71a967743ccab9444185d324196",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":477},
                "size":{
                  "width":157,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u10.jpg"}},
{
          "id":"787aca23c324417bb621ca8bcaa465f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":708},
            "size":{
              "width":176,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eadeb05d0c1a44388d056a9191094a20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":69,
                  "y":708},
                "size":{
                  "width":176,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3dd25e8db10a4436b1328cc2b5d95cff",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":707},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"008577408b3c416e974f5cf6feb27bbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":57,
                  "y":707},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3df13dc2ced64c39a05d1bfadf6bb621",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":109,
              "y":733},
            "size":{
              "width":57,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22bc82806bf54c1cb2c846668a1525bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":109,
                  "y":733},
                "size":{
                  "width":57,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f059155d0b04728953b1af4b271b09f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":751},
            "size":{
              "width":25,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce667b3acf7c4e2f93da8d6668975e25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":751},
                "size":{
                  "width":25,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u18.jpg"}},
{
          "id":"01e6d50378c34c8f839f26405c438a3c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":750},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aef5aef0acf74fb08c07289a73b135b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":750},
                "size":{
                  "width":30,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u20.jpg"}},
{
          "id":"608d175e8ba34d30b17b1b1c24349121",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":133,
              "y":753},
            "size":{
              "width":10,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/收藏夹/u22_line.png"}},
{
          "id":"f9214ab396394e94a54e4a53766a2ad9",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1,
              "y":429},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ac68e6f1f8240389ce044a0fc679627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1,
                  "y":429},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"0b67c5ea44804dbbb352fa99d089361d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":116,
              "y":429},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df7590e3a3f94230a6459a9afd719861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":116,
                  "y":429},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df8a973fdff3485bbc622b7a75993661",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":425},
            "size":{
              "width":25,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2faa22b60cc34ba79c8e643b9375d427",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":425},
                "size":{
                  "width":25,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u18.jpg"}},
{
          "id":"b7fa31b66d99492389d6150c0637ca72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Narrow', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":1,
              "y":367},
            "size":{
              "width":1010,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f61f2418e840f3a4d45b3ad9876e03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Narrow', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":1,
                  "y":367},
                "size":{
                  "width":1010,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u29.png"}},
{
          "id":"29b19418bfcf4117bcef89c020131a13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":463},
            "size":{
              "width":230,
              "height":327}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc2876d3462f4c2fa66a90a303559e8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":463},
                "size":{
                  "width":230,
                  "height":327}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u2.png"}},
{
          "id":"db2eb502ef2f49e5a223c00e975f4611",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":338,
              "y":477},
            "size":{
              "width":190,
              "height":220},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad819f6c679346d2a91934e41a7332e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":338,
                  "y":477},
                "size":{
                  "width":190,
                  "height":220},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u8.png"}},
{
          "id":"f3ff7c800b444c8e9d56202dabe841ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":477},
            "size":{
              "width":157,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9fa747e7998467c875eed3b5090ff1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":351,
                  "y":477},
                "size":{
                  "width":157,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u10.jpg"}},
{
          "id":"af465abb23e54a6089041cd61b57ed9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":708},
            "size":{
              "width":176,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b0cf99b16904e6d92f196e2c9eab1ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":708},
                "size":{
                  "width":176,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"887bbfbc02b0430192c913cd6d1dae55",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":707},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1179d8eae234ec3b935693be2b0e889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":707},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"288dce6c16e7464db4ea4778f047c972",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":733},
            "size":{
              "width":57,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27b228d46612427a80b72815f5cae772",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":733},
                "size":{
                  "width":57,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c7cdf46b41d4bbf8ace8faa91ebf01d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":751},
            "size":{
              "width":25,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeef4de6f28242d9902c692b0ec06f7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":751},
                "size":{
                  "width":25,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u18.jpg"}},
{
          "id":"05d328fdae1c471eb3c07a4849e2f278",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":422,
              "y":750},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0077a119e4d14679af9c5546bf0d9fd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":422,
                  "y":750},
                "size":{
                  "width":30,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u20.jpg"}},
{
          "id":"5b315dc104fb4958a48ce1da758afae1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":414,
              "y":753},
            "size":{
              "width":10,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/收藏夹/u22_line.png"}},
{
          "id":"b94e0085ae7d412284449000434697b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":608,
              "y":463},
            "size":{
              "width":230,
              "height":327}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1899fe9ade1f401ca791d21aa0d1bff1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":608,
                  "y":463},
                "size":{
                  "width":230,
                  "height":327}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u2.png"}},
{
          "id":"b4e21c5759c84d4dbedd55f5fa3cbafe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":619,
              "y":477},
            "size":{
              "width":210,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3866f53c95f4251804d9f8b7bbd3cf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":619,
                  "y":477},
                "size":{
                  "width":210,
                  "height":210}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u50.jpg"}},
{
          "id":"d83a09a98e1743d48340ed74259b140f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":639,
              "y":708},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b046d1040484eba8fa5f545d6477f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":639,
                  "y":708},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"862f5082d2384202ab892b015a1c9ac2",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":707},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a9938191b1149df8cd425443d8df4fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":707},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a9b8c355cac54c23825c0526b99f8132",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":679,
              "y":733},
            "size":{
              "width":57,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a29fda567844adb9259e3ea867cbe8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":679,
                  "y":733},
                "size":{
                  "width":57,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98aad2e38d8e4d50917b2b746566ea74",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":674,
              "y":751},
            "size":{
              "width":25,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2d676a19d97481ba3d8ab87f486f003",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":674,
                  "y":751},
                "size":{
                  "width":25,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u18.jpg"}},
{
          "id":"81aceda64974432b8f91319172a0ca15",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":711,
              "y":750},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ca20fa97982464eb8f92a23572718b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":711,
                  "y":750},
                "size":{
                  "width":30,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u20.jpg"}},
{
          "id":"01ca0509434b42ee86b8dc009154a756",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":703,
              "y":753},
            "size":{
              "width":10,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/收藏夹/u22_line.png"}},
{
          "id":"b0819cbb02164d38b52ac73f9bc389b2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":840},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b7ecb7192cb247b4a5bb94798176e907",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":840},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6d448bb4ceaa4bdc9e779782513afb7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":410,
              "y":844},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e2ff15340784e67a9d22e6c540e71a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":410,
                  "y":844},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc91a87bc4754dc4966151333d38e903",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":900},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"971907f0ffac451894add3962758083e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":900},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4e94e1a3273948289f1988b1750f2277",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":0,
              "y":959},
            "size":{
              "width":1000,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab1603182c94489ca822e6ee960fa110",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":0,
                  "y":959},
                "size":{
                  "width":1000,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u46.png"}},
{
          "id":"66e15ea3f3e24dc0afcc01aed2d36e0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":1000,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c69f73a466c04991a54654e22c2b4eba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":1000,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"0d25d86f4b5749f1899de2a3e7715996",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"6df5494641494e74a42c81eb53f78d16",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"42f931dfb8d34595aa17a47d171acc2b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收藏夹 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"收藏夹.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8cef5f8ec8b34a25882c8e75f164872b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"be01e0fa5caa42eabd5ab6566cf9e01d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":7},
            "size":{
              "width":90,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"766a9e6218ab4a1191adb6215e877494",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":7},
                "size":{
                  "width":90,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"887c8682c7524e3eba0b61dce0ab6020",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":0},
            "size":{
              "width":100,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"5cda1915bdaf4f8c82a20397ff2bd9c5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":0},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"27f8d5f56ffb43e68a38db7d52370b34",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":428},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1248101168fb4a74b291d12587d885fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":428},
                "size":{
                  "width":30,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏夹/u20.jpg"}},
{
          "id":"26a6cdbff1834f9393374bd3a331122b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":220,
              "y":429},
            "size":{
              "width":89,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214f70ac4a37477b993b0c8fefac83f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":220,
                  "y":429},
                "size":{
                  "width":89,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fbe2887575c94f028e80f6798b34fa4e":{
      "scriptId":"u0"},
    "5850559473c04990bf881e8b65c7d17b":{
      "scriptId":"u1"},
    "d8412eb149a643a28ce9cf16c7532b17":{
      "scriptId":"u2"},
    "5b57589ab7514f90be71a543e9dac5f4":{
      "scriptId":"u3"},
    "03ebd25423e246d19407a10d91069a1f":{
      "scriptId":"u4"},
    "5e9b22bd690c4559980f8c020e764577":{
      "scriptId":"u5"},
    "55f8c3353312417fb035a19bebec357d":{
      "scriptId":"u6"},
    "65779c984f9e447cbd8008cd69e89c9a":{
      "scriptId":"u7"},
    "90a94a5adcbc45beb21b9b4da6b4a2c9":{
      "scriptId":"u8"},
    "a6c1ee3fa0ae405099170ab97ba68ef3":{
      "scriptId":"u9"},
    "8cd12f92aed941e3aa4bafbbc07e7def":{
      "scriptId":"u10"},
    "31fff71a967743ccab9444185d324196":{
      "scriptId":"u11"},
    "787aca23c324417bb621ca8bcaa465f2":{
      "scriptId":"u12"},
    "eadeb05d0c1a44388d056a9191094a20":{
      "scriptId":"u13"},
    "3dd25e8db10a4436b1328cc2b5d95cff":{
      "scriptId":"u14"},
    "008577408b3c416e974f5cf6feb27bbe":{
      "scriptId":"u15"},
    "3df13dc2ced64c39a05d1bfadf6bb621":{
      "scriptId":"u16"},
    "22bc82806bf54c1cb2c846668a1525bf":{
      "scriptId":"u17"},
    "6f059155d0b04728953b1af4b271b09f":{
      "scriptId":"u18"},
    "ce667b3acf7c4e2f93da8d6668975e25":{
      "scriptId":"u19"},
    "01e6d50378c34c8f839f26405c438a3c":{
      "scriptId":"u20"},
    "aef5aef0acf74fb08c07289a73b135b8":{
      "scriptId":"u21"},
    "608d175e8ba34d30b17b1b1c24349121":{
      "scriptId":"u22"},
    "f9214ab396394e94a54e4a53766a2ad9":{
      "scriptId":"u23"},
    "8ac68e6f1f8240389ce044a0fc679627":{
      "scriptId":"u24"},
    "0b67c5ea44804dbbb352fa99d089361d":{
      "scriptId":"u25"},
    "df7590e3a3f94230a6459a9afd719861":{
      "scriptId":"u26"},
    "df8a973fdff3485bbc622b7a75993661":{
      "scriptId":"u27"},
    "2faa22b60cc34ba79c8e643b9375d427":{
      "scriptId":"u28"},
    "b7fa31b66d99492389d6150c0637ca72":{
      "scriptId":"u29"},
    "70f61f2418e840f3a4d45b3ad9876e03":{
      "scriptId":"u30"},
    "29b19418bfcf4117bcef89c020131a13":{
      "scriptId":"u31"},
    "bc2876d3462f4c2fa66a90a303559e8e":{
      "scriptId":"u32"},
    "db2eb502ef2f49e5a223c00e975f4611":{
      "scriptId":"u33"},
    "ad819f6c679346d2a91934e41a7332e5":{
      "scriptId":"u34"},
    "f3ff7c800b444c8e9d56202dabe841ea":{
      "scriptId":"u35"},
    "e9fa747e7998467c875eed3b5090ff1a":{
      "scriptId":"u36"},
    "af465abb23e54a6089041cd61b57ed9e":{
      "scriptId":"u37"},
    "6b0cf99b16904e6d92f196e2c9eab1ca":{
      "scriptId":"u38"},
    "887bbfbc02b0430192c913cd6d1dae55":{
      "scriptId":"u39"},
    "f1179d8eae234ec3b935693be2b0e889":{
      "scriptId":"u40"},
    "288dce6c16e7464db4ea4778f047c972":{
      "scriptId":"u41"},
    "27b228d46612427a80b72815f5cae772":{
      "scriptId":"u42"},
    "7c7cdf46b41d4bbf8ace8faa91ebf01d":{
      "scriptId":"u43"},
    "aeef4de6f28242d9902c692b0ec06f7b":{
      "scriptId":"u44"},
    "05d328fdae1c471eb3c07a4849e2f278":{
      "scriptId":"u45"},
    "0077a119e4d14679af9c5546bf0d9fd7":{
      "scriptId":"u46"},
    "5b315dc104fb4958a48ce1da758afae1":{
      "scriptId":"u47"},
    "b94e0085ae7d412284449000434697b3":{
      "scriptId":"u48"},
    "1899fe9ade1f401ca791d21aa0d1bff1":{
      "scriptId":"u49"},
    "b4e21c5759c84d4dbedd55f5fa3cbafe":{
      "scriptId":"u50"},
    "a3866f53c95f4251804d9f8b7bbd3cf2":{
      "scriptId":"u51"},
    "d83a09a98e1743d48340ed74259b140f":{
      "scriptId":"u52"},
    "6b046d1040484eba8fa5f545d6477f81":{
      "scriptId":"u53"},
    "862f5082d2384202ab892b015a1c9ac2":{
      "scriptId":"u54"},
    "2a9938191b1149df8cd425443d8df4fa":{
      "scriptId":"u55"},
    "a9b8c355cac54c23825c0526b99f8132":{
      "scriptId":"u56"},
    "6a29fda567844adb9259e3ea867cbe8c":{
      "scriptId":"u57"},
    "98aad2e38d8e4d50917b2b746566ea74":{
      "scriptId":"u58"},
    "d2d676a19d97481ba3d8ab87f486f003":{
      "scriptId":"u59"},
    "81aceda64974432b8f91319172a0ca15":{
      "scriptId":"u60"},
    "1ca20fa97982464eb8f92a23572718b2":{
      "scriptId":"u61"},
    "01ca0509434b42ee86b8dc009154a756":{
      "scriptId":"u62"},
    "b0819cbb02164d38b52ac73f9bc389b2":{
      "scriptId":"u63"},
    "b7ecb7192cb247b4a5bb94798176e907":{
      "scriptId":"u64"},
    "6d448bb4ceaa4bdc9e779782513afb7b":{
      "scriptId":"u65"},
    "7e2ff15340784e67a9d22e6c540e71a2":{
      "scriptId":"u66"},
    "cc91a87bc4754dc4966151333d38e903":{
      "scriptId":"u67"},
    "971907f0ffac451894add3962758083e":{
      "scriptId":"u68"},
    "4e94e1a3273948289f1988b1750f2277":{
      "scriptId":"u69"},
    "ab1603182c94489ca822e6ee960fa110":{
      "scriptId":"u70"},
    "66e15ea3f3e24dc0afcc01aed2d36e0e":{
      "scriptId":"u71"},
    "c69f73a466c04991a54654e22c2b4eba":{
      "scriptId":"u72"},
    "0d25d86f4b5749f1899de2a3e7715996":{
      "scriptId":"u73"},
    "6df5494641494e74a42c81eb53f78d16":{
      "scriptId":"u74"},
    "42f931dfb8d34595aa17a47d171acc2b":{
      "scriptId":"u75"},
    "8cef5f8ec8b34a25882c8e75f164872b":{
      "scriptId":"u76"},
    "be01e0fa5caa42eabd5ab6566cf9e01d":{
      "scriptId":"u77"},
    "766a9e6218ab4a1191adb6215e877494":{
      "scriptId":"u78"},
    "887c8682c7524e3eba0b61dce0ab6020":{
      "scriptId":"u79"},
    "5cda1915bdaf4f8c82a20397ff2bd9c5":{
      "scriptId":"u80"},
    "27f8d5f56ffb43e68a38db7d52370b34":{
      "scriptId":"u81"},
    "1248101168fb4a74b291d12587d885fa":{
      "scriptId":"u82"},
    "26a6cdbff1834f9393374bd3a331122b":{
      "scriptId":"u83"},
    "214f70ac4a37477b993b0c8fefac83f6":{
      "scriptId":"u84"}}});